### ISSUE TITLE
/oauth/token endpoint returns raw token

### ISSUE THREAD

**Issue by Booyaabes** [gogatekeeper/gatekeeper#103]
# /oauth/token endpoint returns raw token

## Summary

`/oauth/token` endpoint returns raw token with `content-type` set to `application/json`

## Environment

- `quay.io/keycloak/keycloak:13.0.1`
- `quay.io/gogatekeeper/gatekeeper:1.3.2`

## Expected Results

Either gatekeeper returns the decoded token with `content-type` at `application/json`, or it returns the raw token with `content-type` at `application/json;base64`. I think it's more logical that this endpoint returns the decoded token, as I don't see the point otherwise.

## Actual Results

`/oauth/token` endpoint returns raw token with `content-type` set to `application/json`

## Steps to reproduce

just call `/oauth/token` endpoint

## Additional Information

- The endpoint in Gatekeeper 7.0.0 returns the decoded token,
- [The commit that changes endpoint behavior](https://github.com/gogatekeeper/gatekeeper/commit/b07b090523d74321bb62bceeea4a41e876a32f64).

I can change this behavior and make a pull request, but as it's a recent change, a discussion is probably needed.

**Comment by p53** [comment]
@Booyaabes thank you for reporting!

**Comment by Booyaabes** [comment]
@p53 thank you!
