### ISSUE TITLE
/oauth/logout endpoint not working

### ISSUE THREAD

**Issue by Booyaabes** [gogatekeeper/gatekeeper#105]
# `/oauth/logout` endpoint not working

## Summary

Call to `/oauth/logout` endpoint do not cause a user logout.

In logs, I have:

```
gatekeeper_1             | 2021-06-22T14:21:18.689Z     info    successfully logged out of the endpoint {"email": "user@my_domain.com"}
gatekeeper_1             | 2021-06-22T14:21:18.700Z     error   no session found in request, redirecting for authorization      {"error": "authentication session not found"}
gatekeeper_1             | 2021-06-22T14:21:18.742Z     info    issuing access token for user   {"email": "user@my_domain.com", "sub": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx", "expires": "2021-06-22T14:26:18Z", "duration": "4m59.2574955s"}
```

It seems the token is immediatly refreshed.

## Environment

- gogakeeper:1.3.2
- keycloak:13.0.1

## Expected Results

User is effectively disconnected.

## Actual Results

User is not disconnected

## Steps to reproduce

Log, then call to `/oauth/logout` endpoint.

## Additional Information

No additional information

**Comment by Booyaabes** [comment]
Hmm, that's strange, I have just restart everything, and it works again...
I'll try to reproduce the problem and update this issue ASAP.

**Comment by p53** [comment]
@Booyaabes i am using this functionality, i haven't yet problems with it, if you would have any details

**Comment by Booyaabes** [comment]
After somes tests (even really weird ones), I was unable to reproduce the problem. I close this issue.

**Comment by PraserX** [comment]
Hi, I have a same issue. But it is really strange. I have multiple services behind multiple Gatekeepers and somewhere it works fine, but somewhere not. Config is same everywhere.

**Environment**
* gogakeeper:1.3.2
* keycloak:13.0.1
