### ISSUE TITLE
How to use {param} in uri definition

### ISSUE THREAD

**Issue by testuser7** [gogatekeeper/gatekeeper#115]
After update go-chi to new version wildcard '*' must be the last pattern in a route, otherwise we need to use a '{param}'.
How to define {param}?

**Comment by p53** [comment]
@testuser7 can you please describe problem with some example

**Comment by testuser7** [comment]
As of version 1.3.5 it is not possible to define uri `/admin/*/test/*`. 
The error message `wildcard '*' must be the last pattern in a route, otherwise use a '{param}'` is displayed.

**Comment by p53** [comment]
@testuser7 yes, this was bug in go-chi, fixed here https://github.com/go-chi/chi/issues/333

**Comment by testuser7** [comment]
Yes, there was a pattern handling bug.
In my case, I need to define a named param and use in uri definition `/admin/{param}/test/*` but I don't know if it can be done now.

**Comment by p53** [comment]
@testuser7 you cannot do that and it wasn't possible before with gogatekeeper

**Comment by testuser7** [comment]
Is there any chance to add support for named params?
