### ISSUE TITLE
Endpoint for discovery

### ISSUE THREAD

**Issue by RusTigra** [gogatekeeper/gatekeeper#117]
## Summary 

Create "static" endpoint to get some public configuration of Gatekeeper.
Just like [.well-known/openid-configuration]

## Why?

I have some application connecting to Gatekeeper.
For example SPA connecting to API through Gatekeeper.
Application want to use some of service endpoints:
- /oauth/authorize << send user to auth service
- /oauth/logout << to logout user, nothing unusual
- /oauth/token << to check if user has been logined already (cookie authentication)
I don't see any usefullness of other oauth-endpoints for SPA (but I can mistake)

But keyword "oauth" can be modified in config ("oauth-uri")
There are to obvious solutions:
1. Set this keyword in SPA config. It's not stable to further modifications (one setting in two configurations).
2.  [see below]

## How
Make "static" endpoint (just like [/.well-known] in OAuth/OpenId) to obtain public configuration
This endpoint doesn't change route on Gatekeeper configuration changes.

**Comment by p53** [comment]
@RusTigra i think this could be nice feature
