### ISSUE TITLE
Forward Proxy setting "openid-provider-proxy" doesn't work after 1.2.0

### ISSUE THREAD

**Issue by thomaskarras** [gogatekeeper/gatekeeper#122]
# Title

## Summary

I was in the process of upgrading to the latest version, 1.3.6 of gogatekeeper. The previous version we were using was the original keycloak implementation. The environment I'm installing to requires a forward proxy to communicate externally. Version 1.1.0 of gogatekeeper works fine and is able to retrieve the settings from the keycloak server but when I use any version beyond 1.2.0 gatekeeper is stuck trying to retrieve the config from keycloak. The last messages i see in the logs is, 

`info    attempting to retrieve configuration discovery url    {"url": "<keycloak_url>", "timeout": "30s"}
 warn   failed to get provider configuration from discovery	{"error": "<keycloak_url>/.well-known/openid-configuration\": dial tcp <ip>: connect: connection refused"}`

I also do not see any attempts of access on the forward proxy (httpd) 
I am using the docker image for gatekeeper. All config remained the same when swapping between versions other than the tag of gogatekeeper.

## Environment
- OS: Docker running in docker-compose
- Server (e.g. Keycloak or any other IdP): Keycloak
- Gatekeeper: 1.2.0+

## Expected Results

OIDC config successfully retrieved from the Keycloak server through a forward proxy and successful login of a user. 

## Actual Results

Gatekeeper fails trying to retrieve OIDC config

## Additional Information

The issue might be related to where the config is not being passed over the client? I saw that this specific ticket was fixed in gogatekeeper.

https://github.com/louketo/louketo-proxy/issues/657

**Comment by p53** [comment]
thanks for reporting! looked at it seems that oidc client in initialization doesn't use proxy setting and probably that's why you see connection refused, will check where culprit happened

**Comment by p53** [comment]
@thomaskarras i created pull request https://github.com/gogatekeeper/gatekeeper/pull/123, but it doesn't have tests yet, you can build your own docker image in the meantime

**Comment by thomaskarras** [comment]
Thanks! I'll give it a try.

**Comment by p53** [comment]
@thomaskarras there is 1.3.7-rc1 image you can try

**Comment by thomaskarras** [comment]
It works, thank you @p53 for the quick fix!
