### ISSUE TITLE
MethodNotAllowed vs Unauthorized (pull request #110)

### ISSUE THREAD

**Issue by praserx** [gogatekeeper/gatekeeper#142]
@p53 Hi, is it ok on MethodNotAllowed (405) return Unauthorized (401)? I am facing the issue with unknown http method and it is so much confusing if gatekeeper constantly returns Unauthorized with no obvious reason (yeah there is a reason - chi router do no know http method - but it was hard to debug what is wrong).

```Go
if r.config.EnableDefaultDeny {
    engine.MethodNotAllowed(unauthorizedHandler)
} else {
    engine.MethodNotAllowed(emptyHandler)
}
```

The second problem is that MethodNotAllowed request goes through gatekeeper reverse proxy and returns valid response with unauthorized response code.

```Go
// emptyHandler is responsible for doing nothing
func unauthorizedHandler(w http.ResponseWriter, req *http.Request) {
	w.WriteHeader(http.StatusUnauthorized)
}
```

So it seems that only status is added, but propagation do not stopped.

**Comment by p53** [comment]
@praserx i am not sure if this was not some historical simplification, will look at it

**Comment by p53** [comment]
@praserx hi, i checked the code, because we are including HTTP methods in our resource configs (de facto including them in authorization config) we are returning not MethodNotAllowed but 401 (because method in our case of authorization proxy is part of authorization). For example if i would have endpoint /admin and method GET as protected and i will make request on it, it would return of course 401 but if i would have a case where i have default deny and will make request should it return 401 or 405, i think of course 401. Second problem, writing header should finish response.

**Comment by praserx** [comment]
@p53 

### HTTP status

Hmm I am sorry but I cannot agree. According to specification, status code 401 refers to unauthenticated (not logged in) request. If user is authenticated, but lack of some access rights, system should return 403 (forbidden), not 401 (unauthorized).

> Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response. 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses

- If user is **unauthenticated** and accessing protected resource gatekeeper should return **401** (unauthenticated)
- If user is **authenticated** and access protected resource but lack of some access rights gatekeeper should return **403** (forbidden)
- If user is **authenticated** and access protected resource but method is not allowed gatekeeper should return **405** (method not allowed)
- if user is **unauthenticated** and accessing unprotected (white listed) resource but method is not allowed or implemented gatekeeper should return **405** (method not allowed)

### Second problem

The problem is, that user make proper request with valid access rights but with unknown HTTP method (webdav propfind). The request goes through authorization proxy to protected system. System returns response but gatekeeper do not modify or block the communication, but only change response code to 401 (I think there should be 405).

So the user get valid response (valid data from protected resource are returned) but response code is 401. So I think that communication should be blocked at first, but now I can see/get request on/to protected service.

**Comment by p53** [comment]
@praserx yeah we can discuss if it should be 401 or 403 but then of course you would affect existing users and backward compatibility and i think this it not the only place where it returns 401 but should 403....
second problem - understand that's more serious problem i will look at it

**Comment by p53** [comment]
@praserx #144

**Comment by praserx** [comment]
Looks good. I have to update my PR #143 due to [method check](https://github.com/gogatekeeper/gatekeeper/pull/144/files#diff-02f50901140d6057da6310a106670552aa766a093efbc2200fb34c099b762131R645) or feel free to update it.

**Comment by p53** [comment]
@praserx updated your feature in #145
