### ISSUE TITLE
Always deny feature

### ISSUE THREAD

**Issue by garylundie** [gogatekeeper/gatekeeper#167]
When `enable-default-deny: true`, URIs which are not defined in the resources section of the Go-Gatekeeper config are still accessible if any valid authentication token is presented. 

Default deny adds default resource /* - so it is more like enable-default-required-auth feature.

`	if enableDefaultDeny {
		r.log.Info("adding a default denial into the protected resources")

		r.config.Resources = append(
			r.config.Resources,
			&Resource{URL: "/*", Methods: allHTTPMethods},
		)
	}`

Should this flag not force the return a 401/403 for any URI not matching any pattern specified in the Resources configuration?

Is there any other configuration option which would result in an actual default deny?

**Comment by p53** [comment]
@garylundie if i understood your use case correctly you would like to always return 401/403 whether it has token or not, yes enable-default-deny is meant default deny related to auth so maybe enable-default-required-auth would be more precise

**Comment by p53** [comment]
@garylundie but you can achieve similar effect by applying configuration like this https://github.com/gogatekeeper/gatekeeper/blob/master/docs/user-guide.md#white-listed-urls, without enable-default-deny

**Comment by p53** [comment]
@garylundie i added enable-default-deny-strict option, it is in main branch, you can try

**Comment by garylundie** [comment]
@p53 - verified the changes look to achieve the required results.  I've been unable to build locally and will be able to review more fully once the merge is available as a docker image

**Comment by p53** [comment]
@garylundie there is 1.6.0-rc1 image in quay.io repo

**Comment by garylundie** [comment]
Thanks for the update - tested the image and now all working as expected
