### ISSUE TITLE
Question: How to deploy Gatekeeper with Helm alongside to other apps deployed with Helm on Kubernetes

### ISSUE THREAD

**Issue by djessich** [gogatekeeper/gatekeeper#205]
While reading the docs and studying Gatekeeper, a situation came into my mind, resulting in various questions regarding "correct" Kubernetes deployment.

Imagine the following situation:
Deploy an application like Nextcloud into namespace `nextcloud` using Helm chart on a Kubernetes cluster. The helm chart creates a Deployment within Kubernetes for Nextcloud and additional resources required for Nextcloud. Disable Ingress Rule for Nextcloud.

Next, deploy Gatekeeper using the Gatekeeper Helm chart in the same namespace. Let it create a Ingress Rule, so that external requests will be served to Gatekeeper. Gatekeeper needs to be configured to serve the request upon successful authentication and authorization to Nextcloud.

Now there are two Helm charts deployed in a single Kubernetes Namespace. So how is it possible then, that Gatekeeper does know about Nextcloud to redirect to it, in case authentication and authorization is successful? Gatekeeper is NOT a sidecar container in the Nextcloud pod, so how does that work? Is Gatekeeper required to be a sidecar container to work successfully or is it possible that Gatekeeper may resolve Nextcloud using cluster DNS (should be)?

**Comment by djessich** [comment]
@p53 Do you know the correct deployment in Kubernetes alongside other application when both Gatekeeper and the app to be protected are deployed using Helm? Thanks in advance.

**Comment by p53** [comment]
@djessich there is upstream-url parameter, yes you can pass DNS name of service+port to that url, gatekeeper acts as proxy (similar to nginx)

**Comment by p53** [comment]
@djessich i would also consider leaving nginx before gatekeeper as gatekeeper is not fully-fledged proxy and you might need to restrict some http options which are not available in gatekeeper

**Comment by djessich** [comment]
@p53 Thank you for your fast reply. I use Traefik as reverse proxy, but this isn't a problem. In my setup, it is exactly as you said:
User -> Traefik (namespace: x) -> Gatekeeper Pod (namespace: y) -> App Pod (namespace: y). So Gatekeeper comes after Traefik reverse proxy. I'm restricting various App URL endpoints to specific IPs, so I'm required to leave Traefik in front of Gatekeeper.

However, I read during my recherche that Gatekeeper is meant to be a sidecar, which is not always something that can be achieved. When deploying with Helm, it heavily depends on the Helm chart implementation of the App that should be protected (e.g. Nextcloud), if a sidecar container can be deployed (although most Helm charts support that). Besides from that, when using Gatekeeper Helm chart, it is not possible to connect the App Helm chart and Gatekeeper Helm chart to build a pod that uses Gatekeeper as a sidecar. So this is why I was asking how this can be achieved then.

If I understood you correctly then, I just need to pass the Kubernetes cluster-internal DNS name of the app service+port in my Gatekeeper configuration? Well, that's easy :D

Which leads to the question: Gatekeeper is not required to be a sidecar, isn't it?

**Comment by p53** [comment]
@djessich no it doesn't have to be sidecar

**Comment by djessich** [comment]
Ok perfect, so I'll give it a try. Thank you for clarification 👍
