### ISSUE TITLE
Log client_ip with real ip value

### ISSUE THREAD

**Issue by sk1m** [gogatekeeper/gatekeeper#209]
# Log client_ip with real ip value

## Summary 

Set field value "client_ip" to real ip when logging.

## Why?

Currently, field client_ip has value of RemoteAddr, which can be unuseful if gatekeeper placed behind another proxy.

## How

Use `utils.RealIP` result for "client_ip" field value.

**Comment by p53** [comment]
@sk1m understand why it is useful but what if you want to e.g. log both

**Comment by sk1m** [comment]
@p53 agree, much better will be write both
