### ISSUE TITLE
Support keycloak logout in gatekeeper

### ISSUE THREAD

**Issue by YuesIt17** [gogatekeeper/gatekeeper#214]
# Support keycloak logout in gatekeeper
Hi, please tell me if there will be compatibility support for keycloak logout  in gatekeeper.

As written in the documentation https://www.keycloak.org/docs/latest/securing_apps/index.html#_keycloak_generic_adapter 

Description Logout in Keycloak 

> You can log out of a web application in multiple ways. For Jakarta EE servlet containers, you can call HttpServletRequest.logout(). For other browser applications, you can redirect the browser to http://auth-server/realms/{realm-name}/protocol/openid-connect/logout, which logs the user out if that user has an SSO session with his browser. The actual logout is done once the user confirms the logout. You can optionally include parameters such as **id_token_hint**, **post_logout_redirect_uri**, client_id and others as described in the [OpenID Connect RP-Initiated Logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html). As a result, that logout does not need to be explicitly confirmed by the user if you include the **id_token_hint** parameter. After logout, the user will be automatically redirected to the specified post_logout_redirect_uri as long as it is provided. Note that you need to include either the client_id or id_token_hint parameter in case that post_logout_redirect_uri is included.

That is, the ability to support parameters **id_token_hint** and **post_logout_redirect_uri**  in gatekeeper?

**Comment by p53** [comment]
@Mikh36 yes it will be supported as it affects current funcionality of gatekeeper

**Comment by p53** [comment]
@YuesIt17 @Mikh36 just FYI, not sure if this could fit you - logout solution independent of this keycloak change with gatekeeper could be /oauth/logout?redirect=your-redirect-url (with bearer token in headers), r.config.EnableLogoutRedirect=false, this will revoke current access token
