### ISSUE TITLE
Build for arm and arm64 architectures

### ISSUE THREAD

**Issue by rekup** [gogatekeeper/gatekeeper#244]
# Build for arm and arm64 architectures

## Summary 

We would really love to extend the existing goreleaser config to include builds for arm and arm64 architectures

## Why?

With arm build we would be able to run gatekeeper on devices such as raspberry pi and other borads with arm architecture

## How

By extending the existing [.goreleaser.yml](https://github.com/gogatekeeper/gatekeeper/blob/master/.goreleaser.yml) file.

## Acceptance criteria

We have additional builds for the following architectures:

- linux-armv6
- linux-armv7
- linux-arm64

**Comment by p53** [comment]
i am a little bit concerned about bugs/problems with arm/go/libraries but we can try to support it for now and let's see if there will be problems
