### ISSUE TITLE
HTTP vs HTTPS redirection when used behind a TLS terminating proxy

### ISSUE THREAD

**Issue by jonkerj** [gogatekeeper/gatekeeper#253]
## Summary

Since #240, [the way the redirect URL is constructed](https://github.com/gogatekeeper/gatekeeper/blob/master/handlers.go#L62-L73) depends on the contents of `req`, instead of headers being present. In our situation, we run gatekeeper behind a TLS terminating proxy (nginx-ingress inside Kubernetes), so `req` "thinks" there is no TLS, causing `getRedirectionURL` to create HTTP URLs instead of HTTPS.

If I'm not mistaken, the only relevant config option is setting `--no-proxy true`, but this also disables the proxy, which I certainly don't want.

## Environment
- OS: Talos Linux
- Kernel: 5.15.89-talos
- Go: n/a
- Server: keycloak
- Gatekeeper: 2.1.0 and 2.1.1

## Expected Results
I would expected one of these things:
- config to tell gatekeeper to "trust" the headers
- config to override the scheme
- some smart mechanism that automatically picks the right scheme for every possible situation 😉 

## Actual Results
- gatekeeper mis-guessing the scheme (http)

## Steps to reproduce
- install gatekeeper 2.1.x on Kubernetes
- random upstream app (echo server)
- ingress controller with TLS termination in front of it, which has HTTP-HTTPS redirects disabled (or a firewalled port tcp/80)

## Additional Information
I'd like to PR a solution, but I'm unsure which of the two expected results is preferred. Either is fine and I think overriding the scheme in config makes the most sense (it seems common in other applications)

**Comment by p53** [comment]
@jonkerj there is --redirection-url parameter

**Comment by p53** [comment]
i was thinking also about that trust option, but you know it is very easy for newcomer set something to trust without thinking about what it might cause, so that's why i didn't implement it

**Comment by jonkerj** [comment]
> @jonkerj there is `--redirection-url` parameter, you can set it to properly redirect

Whoops, I totally missed that. Thanks for pointing out.

> i was thinking also about that trust option, but you know it is very easy for newcomer set something to trust without thinking about what it might cause, so that's why i didn't implement it

Yeah, same. If you were to implement it, I would have users opt-in for that trust, disabling it by default for that reason.

**Comment by zbarnett** [comment]
@p53 first off, thank you so much for maintaining Gatekeeper!

I just ran into this same issue but I have multiple valid domains the users could be coming in from so I'm unable to use the `--redirection-url` parameter. The host header is getting me most of the way there but the load balancer is terminating TLS so Gatekeeper is redirecting to http:// instead of https://.

I realize trusting the `X-Forwarded-*` headers blindly is dangerous, but would it be reasonable to trust only `X-Forwarded-Proto` if it would cause the scheme to go from `http` to `https`?

As the code stands it looks like:

```golang
if req.TLS != nil {
    scheme = constant.SecureScheme
}
```

But what if it was:

```golang
if req.TLS != nil || req.Header.Get("X-Forwarded-Proto") == constant.SecureScheme {
    scheme = constant.SecureScheme
}
```

I can put in a PR if this is something you would accept.

**Comment by zbarnett** [comment]
@p53 I was looking into the forward-auth option as well. It does look appealing for some other reasons besides this, but it would require changing our infrastructure a bit.

This is what our setup looks like currently:
```mermaid
graph LR;
    subgraph ide1 [K8 Pod]
    B(Gatekeeper) --> C(App)
    end

    A(K8 Ingress<br>maindomain.com<br>seconddomain.com) --> B
```

We want the app protected by Gatekeeper to be available on both domains at the same time and whichever domain the user initiates the login process from, to be redirected back to after the login is complete. This is pretty much working but the only issue is the user is redirected back to `http://seconddomain.com` returning from Keycloak when they had originally started on `https://seconddomain.com` We have an http to https redirect set up so they end up in the right spot, but it would be ideal if they never fell back to http in the first place.

**Comment by p53** [comment]
@zbarnett I understand. You can use two gatekeepers, although of course it won't be so effective. Will need to think about it, don't like idea of just accepting headers from user input by default
