### ISSUE TITLE
Erroneously Url Encoding For Basic Auth Header on Logout

### ISSUE THREAD

**Issue by systemtrap** [gogatekeeper/gatekeeper#261]
# Erroneously Url Encoding For Basic Auth Header on Logout

## Summary
On logout client id and client secret are URL-encoded before using them as username and password in the basic authorization header.

## Environment
any

## Expected Results
* HTTP reponse code 200
* destruction of the session held by the IdP.

## Actual Results
* HTTP reponse code 500
* session remains
* log contains `invalid response from revocation endpoint    {"status": 400, "response": "{\"error\":\"invalid_client\",\"error_description\":\"INVALID_CREDENTIALS: Invalid client credentials\"}"}`

## Steps to reproduce
1. configure a client containing '@' symbol
2. login
3. logout

## Additional Information
Either do not encode client id and client secret at all or send them as part of the form encoded body.
see https://github.com/gogatekeeper/gatekeeper/blob/master/handlers.go#L776

**Comment by p53** [comment]
Thanks for opening issue, i will need to check history why it was made the way it is now

**Comment by p53** [comment]
hmm from what i see in history i think it was added errorneously

**Comment by systemtrap** [comment]
Interesting to say the least. I'd based my statements on RFC7616 in particular on
https://www.rfc-editor.org/rfc/rfc7617#section-2
```
For the user-id, recipients MUST support all characters defined in
the "UsernameCasePreserved" profile defined in Section 3.3 of
[RFC7613], with the exception of the colon (":") character.
```

I did not find any additional clue about encoding the username any further. It fails for KC when the client identifier contains characters being encoded and work fine otherwise. I'll searching the KC sources to see, if the is any hint of decoding the client identifier.

**Comment by systemtrap** [comment]
Thanks for pointing me to RFC6749. This leads directly to [Keycloak#11908](https://github.com/keycloak/keycloak/issues/11908). Fortunatly upgrading Keycloak is already planned.
