### ISSUE TITLE
Gatekeeper still watching the header Authorization even if enable-authorization-header option is false

### ISSUE THREAD

**Issue by vc43** [gogatekeeper/gatekeeper#266]
# Title

Gatekeeper still watching the header Authorization even if  enable-authorization-header=false

## Summary
I'm using an application with built-in authorization and it sets (by Java Script) the header `Authorization: Bearer ...`. Gatekeeper in this case gives an error ` oidc: id token issued by a different provider`

## Environment
- Server: keycloak 20.0.3
- Gatekeeper: docker 2.2.0

## Expected Results
Gatekeeper passes traffic.

## Steps to reproduce
Send a request whith the header Authorization.
## Additional Information

I think that with the enable-authorization-header=false, the gatekeeper should ignore the Authorization header that comes from the user and pass it on to the application.

**Comment by p53** [comment]
Hi, please check gatekeeper --help, there you see all short descriptions of parameters or in https://gogatekeeper.github.io/gatekeeper/configuration, agree that on github.io it could be describe a little more (will update) but shortly, this options turns off/on adding/removing Authorization header to request to upstream (means your service behind gatekeeper). For your usage (not sure about details) seems that you will need –skip-authorization-header-identity or –skip-token-verification

**Comment by vc43** [comment]
@p53 thanks a lot.
