### ISSUE TITLE
Readme "writing tests" link leads to 404

### ISSUE THREAD

**Issue by ILyaCyclone** [gogatekeeper/gatekeeper#272]
## Summary

Current [README.md](https://github.com/gogatekeeper/gatekeeper/blob/master/README.md) "writing tests" link in [Writing tests](https://github.com/gogatekeeper/gatekeeper/blob/master/README.md#writing-tests) section has `https://github.com/gogatekeeper/gatekeeper/blob/master/docs/tests-development.md` href which leads to "404 - page not found".

## Expected Results

Get browser to "Writing tests" page or section.

## Actual Results

Github 404 page.

## Steps to reproduce

In browser click on "writing tests" link in [Writing tests](https://github.com/gogatekeeper/gatekeeper/blob/master/README.md#writing-tests) section.

## Additional Information

Permalink to current README.md: https://github.com/gogatekeeper/gatekeeper/blob/09c229ba66a7e21f53766c3344d0b53cb66a9e73/README.md

**Comment by p53** [comment]
thanks for reporting, i removed that .md file because it didn't contain any very much useful docs (if you check older releases), but forgot that i have link down there, will fix

**Comment by p53** [comment]
removed link
