### ISSUE TITLE
Redundant slash in  redirect url with basic config no-proxy

### ISSUE THREAD

**Issue by Jufik** [gogatekeeper/gatekeeper#275]
# Wrong  redirect url with basic config no-proxy
## Summary

Gatekeper 2.3.0 running with latest Helm Chart.

```
discovery-url: {{ $.client_endpoint }}
client-id: {{ $.client_id }}
client-secret: {{ $.secret_oidc }}
listen: :3000
listen-admin: :4000
enable-refresh-tokens: true
encryption-key: {{ $.encryption_key }}
no-proxy: true
```
Running: 
`curl http://service.namespace.svc.cluster.local  --header "X-Forwarded-Proto: https" --header "X-Forwarded-Host: my-domain" --header "X-Forwarded-Uri: /" `

## Expected Results

Server should redirect to:
`my-domain/oauth/callback?authorize?state=...`

## Actual Results

Server should redirect to:
`my-domain/oauth//callback?authorize?state=...`
(note the slash duplication)

## Investigation

Disclaimer: I know nothing in Go.

Looking here:
https://github.com/gogatekeeper/gatekeeper/blob/323f48085dcf08ac4dd22001fa9bb0b18f74d6f5/pkg/config/config.go#L398-L403

here:
https://github.com/gogatekeeper/gatekeeper/blob/323f48085dcf08ac4dd22001fa9bb0b18f74d6f5/pkg/constant/constant.go#L17

and here: 
https://github.com/gogatekeeper/gatekeeper/blob/323f48085dcf08ac4dd22001fa9bb0b18f74d6f5/misc.go#L254

I'd say that's pretty logic, but once again, there might be some magic trick I'm not aware of.

**Comment by p53** [comment]
thanks for reporting, it is minor issue, will look at it
