### ISSUE TITLE
Support other IDPs

### ISSUE THREAD

**Issue by dvob** [gogatekeeper/gatekeeper#292]
## Summary 
Support other OIDC compliant IDPs.

## Why?
Currently Gatekeeper only accepts OIDC issuer URLs which correspond to the format Keycloak uses.
Gatekeeper is a convenient tool and I would like to also use it in scenarios where no Keycloak is involved.

## How
Remove/change parts which actively prevent using Gatekeeper with other OIDC Issuer URLs.
The main thing i ran into was this: https://github.com/gogatekeeper/gatekeeper/blob/master/pkg/config/config.go#L969

I changed this (see https://github.com/dvob/gatekeeper/commit/d5ef11ba32c001f363ec90c933c11d9cb0b8e4bc) which in a first quick test made it work for my use case. But I didn't deeply look into it so I don't know what kind of implications setting Realm to an arbitrary value has.

But before I look deeper into it I wanted ask if potential PRs to make gatekeeper more generic would be accepted at all?

## Acceptance criteria
Gatekeeper can be used with other OIDC compliant IDPs other than Keycloak.

**Comment by p53** [comment]
even when somewhere is specified that IdP is OIDC compliant there might be plenty of small differences in implementation which can broke code so i think this would need major refactor of all code, refactor is needed anyway but i don't think introducing another layers would help right now, so i am not against experimenting, if you try some provider and make it work i would be happy to see what needs to be changed and where but from the point of time i don't have so much time and from point of code organization i think it would need quite and lot of work to make it organized/well tested

**Comment by morelina** [comment]
Old louketo proxy used to work with different OIDC PROVIDERS. Right now, they cannot be integrated as Gogatekeeper will validate the discovery-url with a regex that requires the keycloak path structure (realms/{realm-id}).
