### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by PraserX** [gogatekeeper/gatekeeper#3]
Hi there,

I don't know if it is a feature or bug report, but is it possible to publish new (first) release with some binary assets? I know that there is no new feature or something, but I migrating my projects from Louketo proxy to this Gatekeeper. It would make my job much easier.

Thanks.

**Comment by p53** [comment]
working on it

**Comment by p53** [comment]
@PraserX made 1.1.0-rc1 release, can you try if everything is smooth, should not be problems because tried to not do any unneeded changes

**Comment by p53** [comment]
@PraserX 1.1.0 was released
