### ISSUE TITLE
Inaccuracy in documentation

### ISSUE THREAD

**Issue by hillout** [gogatekeeper/gatekeeper#300]
# User Guide

## Inaccuracy in documentation

Almost at the near of the bottom:

### Request tracing 
"Usually when there are multiple http services involved in serving user requests you need to use X-REQUEST-ID or some other header to track request flow through services. To make this possible with gatekeeper you can enable header logging by enabling **--enable-logs** and --verbose options. Also you can use request-id-header and enable-request-id options, which will generate unique uuid and will inject in header supplied in request-id-header option."

There is no **--enable-logs** options, there is only --enable-logging.

**Comment by p53** [comment]
+1, will fix
