### ISSUE TITLE
Returned empty "token_type" if using relay endpoint to login '/oauth/login'

### ISSUE THREAD

**Issue by plmikhail** [gogatekeeper/gatekeeper#324]
# Returned empty "token_type" if using relay endpoint to login '/oauth/login'

## Summary
When using relay endpoint to login returned empty "token_type":

`curl -X POST -d "username=test" -d "password=test" "http://127.0.0.1/oauth/login"`
{
  "token_type": "",
  "access_token": "C7IYtAaUu...",
  "id_token": "tlrMA5Cwu...",
  "refresh_token": "NosOwCUsQ...",
  "expires_in": 300,
  "scope": "openid email profile"
}

if request token directly from keycloak all good:
`curl -s -d "client_id=my-app" -d "client_secret=some_secret" -d "username=test" -d "password=test" -d "grant_type=password" https://auth.example.com/realms/my-realm/protocol/openid-connect/token`
{
  "access_token": "Lj6B32/9N...",
  "expires_in": 300,
  "refresh_expires_in": 600,
  "refresh_token": "BCjRYRNx/...",
  "token_type": "Bearer",
  "scope": "email profile"
  ...
}

## Environment
- Gatekeeper: 2.6.2

**Comment by p53** [comment]
Hi, thanks for reporting! Will have a look.

**Comment by p53** [comment]
@plmikhail it is fixed, there is also 2.6.3-rc1 image

**Comment by plmikhail** [comment]
It works, thank you!
