### ISSUE TITLE
SameSite=None doesn't appear in set-cookie

### ISSUE THREAD

**Issue by facetious** [gogatekeeper/gatekeeper#330]
## Summary
When specifying `--same-site-cookie=None`, the `set-cookie` instruction does not contain the `SameSite=None` directive and instead issues no `SameSite` instruction at all, leaving it up to the client to choose its own default. In the case of Chrome, it defaults to `Lax`, not `None`.

## Expected Results
`SameSite=None` should be present in the `set-cookie` instruction.

## Actual Results
`SameSite` is undeclared in the `set-cookie` instruction.

**Comment by p53** [comment]
@facetious created 2.7.0-rc1 release=image
