### ISSUE TITLE
[Support]: How to decrypt access token

### ISSUE THREAD

**Issue by hillout** [gogatekeeper/gatekeeper#341]
Hi, 

Sorry for writing it here, but couldn't find the info in the docs. By using –enable-encrypted-token I can see the access token in being encrypted. How can I properly decrypt it? I tried aes256, which I specified in –encryption-key - but that didn't work. 

Asking cuz - we tried to develop single sing out - but every time when we, for example, log in into two services (standing behind gatekeeper) and call /oauth/logout on service 2 (for example), service 1 is still being logged in until access token is expired. So, we solved it by removing http-only flag for deleting cookies once backend checks /userinfo in Keycloak (that's the way we get roles and groups for user and at the same time check KC user session is alive) and send us 401.  And then service 1 after being refreshed log out instantly. Downside is - http only flag is off, which is not very secure, and I decided maybe at least to encrypt the access token and decrypt it on backed for sending an API request to /userinfo Keycloak endpoint.

Maybe we're doing it completely wrong ?

**Comment by p53** [comment]
Please check logout documentation for gatekeeper, there are several options for logout described https://gogatekeeper.github.io/gatekeeper/userguide/#logout-endpoint

**Comment by hillout** [comment]
Maybe I wasn't a bit clear. I tried two logout options: 
1. Using gatekeeper own mechanism
2. Using Keycloak mechanism
Both working differently, first one log you out from the client, second one logout from all clients in Keycloak. So, the second one is more preferable. But the thing is when you're logging out from service one, you're still staying logged in into service two until the Access Token is expired (cuz it's still valid), and I try to find the best way - for the case: once you log out from the service one, 
 service two (the next tab in browser) after refreshing the page you get instantly redirected to KC (or the other page specified in --post-logout-redirect).

**Comment by p53** [comment]
thanks for adding details, it is now more clear, i will look into possible solutions, meanwhile it is aes128-gcm (16-byte cipher) or aes256-gcm (32-byte cipher)

**Comment by hillout** [comment]
Wow! Will do and get back with response asap.

**Comment by hillout** [comment]
Aaand it works! 

But with --enable-logout-redirect=**true**, so all user sessions on all clients in Keycloak are being logged out by using Keycloak mechanism. Now after initiating /oauth/logout on service 1 and refreshing page with service 2 it redirects to Keycloak like a charm, great!

What api at Keycloak are you using for checking session?

**Comment by hillout** [comment]
Keycloak 22.0.1

My config of GK:

      - "--enable-logging=true"
      - "--enable-json-logging=false"
      - "--enable-refresh-tokens=true"
      - "--verbose=true"
      - "--client-id=pihole-pi4"
      - "--client-secret=somerandomekey"
      - "--discovery-url=https://keycloak.duckdns.org/realms/network/.well-known/openid-configuration"
      - "--listen=:5556"
      - "--upstream-url=http://pihole:80/admin/"
      - "--redirection-url=https://service.mydomain.com"
      - "--encryption-key=somerandomekey"
      - "--enable-default-deny=true"
      - "--skip-access-token-clientid-check=true"
      - "--skip-access-token-issuer-check=true"
      - "--enable-authorization-header=true"
      - "--enable-session-cookies=true"
      - "--enable-logout-redirect=true"
      - "--post-logout-redirect-uri=https://google.com"
      - "--enable-idp-session-check"

**Comment by p53** [comment]
and configuration of second client is same right (except creds)?

**Comment by hillout** [comment]
Yep, same. Here some KC settings (but I don't think they significant): 

<img width="787" alt="Снимок экрана 2023-09-27 в 00 20 01" src="https://github.com/gogatekeeper/gatekeeper/assets/15137897/855d7f15-d4ec-47c1-b5df-31bca63682aa">
<img width="647" alt="Снимок экрана 2023-09-27 в 00 19 24" src="https://github.com/gogatekeeper/gatekeeper/assets/15137897/483a2835-7796-41dc-9315-d25d009891ff">


<img width="787" alt="Снимок экрана 2023-09-27 в 00 21 29" src="https://github.com/gogatekeeper/gatekeeper/assets/15137897/6b615257-4774-4a64-991c-e83b1064089d">

<img width="1078" alt="Снимок экрана 2023-09-27 в 00 22 15" src="https://github.com/gogatekeeper/gatekeeper/assets/15137897/b5e4ec61-eef6-4805-95ab-460e9afdc1f7">

**Comment by hillout** [comment]
Tried on our working projects - working as expected. Did you manage to replicate it?

**Comment by p53** [comment]
hi, didn't have time yet from yesterday, now i am in work...but will look at it and on your options in keycloak

**Comment by p53** [comment]
@hillout ok tested now, works as you said for your use case, i additionally found one thing that when --enable-redirect-logout=false it logouts all sessions when there are 2 windows and one client but it doesn't work with 2 win and 2 clients in any way true/false

**Comment by hillout** [comment]
@p53 hi! Hm, strange cuz at my side it works this way (and it worked that way always):

Situation 1:
2-3-4 (whatever number of services (which are clients in KC)) logged in. 
Using "--enable-redirect-logout=**false**" and if I go to https://service1/oauth/logout, it logs out only this client, I can see it judging by KC panel at the "Session" page. And if I again go to the same https://service1 it logs in via SSO again. 

Situation 2: 
2-3-4 (whatever number of services (which are clients in KC)) logged in. 
Using -enable-redirect-logout=**true** at this time, and going to https://service1/oauth/logout, it logs out all the clients - thus services 1-2-3-4 are erased from user session, judging by KC panel at "Session" page. And now if I go to whatever service I'm getting redirected to KC for authentication.

I can provide you some video, or if you'll have some spare time we can arrange a zoom call - show you.

**Comment by p53** [comment]
yeah those are your scenarios, i can make table:
                                                       TRUE                                        FALSE          
 | two tabs | 2 clients          |     :heavy_check_mark:   | :x
 | two win  | 2 clients           |    :x:                                   | :x
 | two win  | 1 one client    |     :x:                                   | :heavy_check_mark: 
 | two tabs | 1 one client    |     :heavy_check_mark:   | :heavy_check_mark:

**Comment by hillout** [comment]
Oh, win != tab, just got it. But in my case: 

| Scenario | Clients | TRUE | FALSE
| two tabs | 2 clients | ✔️ | :x
| two win | 2 clients | ✔️ | :x
| two win | 1 one client | ✔️ | ✔️
| two tabs | 1 one client | ✔️ | ✔️

Two windows mean two separate tab in different windows of Chrome (right?). If it's gonna be like - one is in incognito mode, second is in general mode - than results would be differ.

**Comment by p53** [comment]
:) i was trying one win in firefox and one chrome, so one more variation to try

**Comment by hillout** [comment]
@p53 hahaha, yeah for sure. All good then, waiting for the release, thanks!
