### ISSUE TITLE
Gatekeeper with NGINX auth_request

### ISSUE THREAD

**Issue by daniel-pimenta-DME** [gogatekeeper/gatekeeper#353]
# Title
Gatekeeper with NGINX auth_request

## Summary 

Hello
I've tried to use Gatekeeper to authenticate/authorize users using NGINX with [auth_request module](https://nginx.org/en/docs/http/ngx_http_auth_request_module.html), but unable to get it working.
The flow I am trying to achieve is this (ignoring cookies):
user -> nginx -> backend -> 401 -> nginx auth_request -> gatekeeper -> keycloak -> user signs in -> gatekeeper -> nginx -> backend -> reply to user
When i tried that setup, gatekeeper returns 303 See other to nginx auth_request which is treated as an error, as of specification of auth_request
"If the subrequest returns a 2xx response code, the access is allowed. If it returns 401 or 403, the access is denied with the corresponding error code. Any other response code returned by the subrequest is considered an error."

**Gatekeeper config**
```
  client-id: ...
  client-secret: ...
  discovery-url: http://identity-keycloak:8080/realms/master
  secure-cookie: false
  skip-openid-provider-tls-verify: true
  no-proxy: true
  enable-default-deny: true
  encryption-key: ...
  listen: :3000
  listen-admin: :4000
  enable-metrics: true
  enable-logging: true
  enable-request-id: true
  enable-login-handler: true
  enable-refresh-tokens: true
```
  
**Nginx config**
```
location / {
        root /data/www;
        proxy_pass http://resource-server:7072;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Host $host:80;
        proxy_set_header X-Forwarded-Port 80;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 1;
        proxy_read_timeout 30;
        proxy_send_timeout 30;
        proxy_http_version 1.1;
        auth_request /oauth/authorize;
        auth_request_set $user   $upstream_http_x_auth_request_user;
        auth_request_set $email  $upstream_http_x_auth_request_email;
        proxy_set_header X-User  $user;
        proxy_set_header X-Email $email;
        auth_request_set $token  $upstream_http_x_auth_request_access_token;
        proxy_set_header X-Access-Token $token;
        auth_request_set $auth_cookie $upstream_http_set_cookie;
        add_header Set-Cookie $auth_cookie;
        auth_request_set $auth_cookie_name_upstream_1 $upstream_cookie_auth_cookie_name_1;
        if ($auth_cookie ~* "(; .*)") {
            set $auth_cookie_name_0 $auth_cookie;
            set $auth_cookie_name_1 "auth_cookie_name_1=$auth_cookie_name_upstream_1$1";
        }
        if ($auth_cookie_name_upstream_1) {
            add_header Set-Cookie $auth_cookie_name_0;
            add_header Set-Cookie $auth_cookie_name_1;
        }
}

location = /oauth/authorize {
        internal;
        proxy_pass http://gatekeeper:3000/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Port 80;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header Content-Length "";
        proxy_intercept_errors on;
        error_page 303 = @handle_redirect;
}

location @handle_redirect {
        set $redirect_location 'http://gatekeeper:3000/$upstream_http_location';
        proxy_pass $redirect_location;
        proxy_intercept_errors on;
        error_page 303 = @handle_redirect_auth;
}

location @handle_redirect_auth {
        set $auth_redirect_location '$upstream_http_location';
        proxy_pass $auth_redirect_location;
 }
```

**Gatekeeper logs**

>  info    accces token for user has expired, attemping to refresh the token       {"client_ip": "172.22.0.1", "remote_addr": "172.22.0.7:53070", "email": "", "sub": "5db927ed-53f6-4fe1-8b07-e0b608bbe006"}
>  warn    refresh token has expired, cannot retrieve access token {"client_ip": "172.22.0.1", "remote_addr": "172.22.0.7:53070", "email": "", "sub": "5db927ed-53f6-4fe1-8b07-e0b608bbe006"}
>  info    client request  {"latency": 0.00566194, "status": 303, "bytes": 86, "client_ip": "172.22.0.1", "remote_addr": "172.22.0.7:53070", "method": "GET", "path": "/"}
>  info    client request  {"latency": 0.000054795, "status": 303, "bytes": 297, "client_ip": "172.22.0.1", "remote_addr": "172.22.0.7:53074", "method": "GET", "path": "/oauth/authorize"}

**Nginx logs**
> 172.23.0.1 - - [06/Oct/2023:21:22:54 +0000] "GET / HTTP/1.1" 500 579 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "-"
> [error] 30#30: *3 auth request unexpected status: 303 while sending to client, client: 172.23.0.1, server: resource-server-gatekeeper, request: "GET / HTTP/1.1", host: "localhost"

**Comment by p53** [comment]
problem here is that auth_request module doesn't count that gatekeeper will do full code flow, forward-auth should be used only for yes/no decisions. It is only feature of gatekeeper that it does full code flow, not just simple yes/no...

**Comment by daniel-pimenta-DME** [comment]
Thank you
For anyone looking to use it with nginx-ingress:
` nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request /auth;
  nginx.ingress.kubernetes.io/server-snippet: |
      location ^~ /auth {
        internal;
        proxy_pass <gatekeeper-url>;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Method $request_method;
        proxy_set_header X-Forwarded-URI $request_uri;
      }`
Gatekeeper config:
  no-redirects: true
  no-proxy: true
  ...
