### ISSUE TITLE
Upgrading past 2.6.3 breaks deployment

### ISSUE THREAD

**Issue by harpunius** [gogatekeeper/gatekeeper#398]
# Upgrading past 2.6.3 breaks our dockerised deployment

## Summary
Upgrading from 1.8.1 to the latest version broke our deployment. We managed to pinpoint version 2.6.3 as the version where things stopped working.
 
## Environment
- OS: Linux
- Kernel (e.g. `uname -a`): Linux ip-10-151-96-182 5.15.0-1050-aws #55~20.04.1-Ubuntu SMP Mon Nov 6 12:15:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Server (e.g. Keycloak or any other IdP): Keycloak
- Gatekeeper: 2.6.3
- Docker Compose version v2.23.3

## Expected Results
With no breaking update guide, I expected to be able to upgrade to v2.

## Actual Results
Upgrading past 2.6.3 (any version, we tried 2.7.x, 2.8.x, 2.9.x) crash-loops the container.

## Steps to reproduce
docker-compose.yaml file with the following
```
  gatekeeper:
    container_name: gatekeeper
    image: quay.io/gogatekeeper/gatekeeper:2.9.0 (or 2.6.3 or anything inbetween)
    restart: always
    command: [
      "--resources=uri=/*|roles=devops-admin,devops-write|require-any-role=true",
    ]
```

and run it with
`docker compose -f docker-compose.yaml up gatekeeper`.

This results in
```
[error] invalid resource devops-write|require-any-role=true, invalid resource keypair, should be (uri|roles|headers|methods|white-listed)=comma_values
```

Prior to version 2.6.3, this does not happen and gogatekeeper parses the `--resources`  correctly.

## Additional Information

We tried wrapping the command in double-quotes, single-quotes etc, but to no avail (only the error message changed slightly, but parsing still fails). 

My guess is the upgrade to urfave/cli/v2 broke some parsing. I found this interesting issue about comma-containing fields and [this case](https://github.com/urfave/cli/issues/1134#issuecomment-1272105669) that it's supposed to fix. Looks like our case.

**Comment by p53** [comment]
@harpunius thanks for reporting! will look at it

**Comment by p53** [comment]
@harpunius , fixed, you can try 2.9.3-rc3

**Comment by harpunius** [comment]
Works, thanks a lot for the quick solution! Do you have an ETA on when this will be released?

**Comment by p53** [comment]
@harpunius today
