### ISSUE TITLE
Access token for websocket connection setup is not visible while in query string

### ISSUE THREAD

**Issue by Bogdan00766** [gogatekeeper/gatekeeper#421]
# Title
Access token for websocket connection setup is not read while in query string

## Summary

When i'm trying to use gatekeeper to secure access to websocket i have error "no session found". After gatekeeper source code analyze i found out that it can't read token from querystring but it is recommended for websocket connections. Could you add that function?

Used with Microsoft signalR React

## Expected Results
Gatekeeper can read token from queryString
## Actual Results
Gatekeeper can't read token from queryString

**Comment by p53** [comment]
it is in cookies, could you use that, it is safer from security perspective as query strings are usually logged on web servers, effectively logging credentials

**Comment by Bogdan00766** [comment]
> @Bogdan00766 it is in cookies, could you use that, it is safer from security perspective as query strings are usually logged on web servers, effectively logging credentials

I can't see that option in Microsoft React SignalR library. How Can i pass it as cookie?

**Comment by p53** [comment]
not sure about this library, i've never seen it but this seems related: https://learn.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-8.0

**Comment by Bogdan00766** [comment]
It's not the answer. You sent me article about .NET, not React.

**Comment by p53** [comment]
@Bogdan00766 sorry this is not forum for solving programming tasks

**Comment by p53** [comment]
for recommendation on bearer tokens https://www.rfc-editor.org/rfc/rfc6750#section-5.3 => Don't pass bearer tokens in page URL

**Comment by Bogdan00766** [comment]
It is safe due to:
https://faqs.ably.com/is-it-secure-to-send-the-access_token-as-part-of-the-websocket-url-query-params
Gatekeeper should support access_token in query params. It is default way to secure websockets

**Comment by p53** [comment]
@Bogdan00766 issue is not only logs for proxies but also logs of webservers, those are viewable by server administrators and additionally nowadays usually also forwarded to log aggregation platforms, so anyone who has access to these resources might misuse it...

**Comment by Bogdan00766** [comment]
Yeah, sure. But still browsers do not supports Authorization headers with websocket. So gatekeeper can't work to protect that.

**Comment by p53** [comment]
:) i am pretty sure they can send cookies, checked now source code https://github.com/dotnet/aspnetcore/blob/14868cc8741fda987431003ea3b06ac01e7fc3f1/src/SignalR/clients/ts/signalr/src/IHttpConnectionOptions.ts#L62 here it seems that it should send cookies by default, could you please check your request if it is sending cookies? could you please also provide configuration of gatekeeper thx

**Comment by Bogdan00766** [comment]
I have withCredentials:true.
gatekeeper config without sensitive data(working for rest endpoints, not working for WS):
`skip-upstream-tls-verify: false
skip-openid-provider-tls-verify: true
listen: 0.0.0.0:3000
secure-cookie: false
enable-logging: true
enable-json-logging: true
enable-default-deny: true
enable-refresh-tokens: true
enable-session-cookies: true
debug: true
ingress.enabled: true
resources:
- uri: /favicon
  white-listed: true
- uri: /state/*
  roles: 
  - user
  methods:
  - GET
  - POST
  - OPTIONS
enable-cors: true
allow-credentials: true
cors-origins: etc.`

**Comment by p53** [comment]
did you check request if cookies are sent?

**Comment by p53** [comment]
did you check same-site cookie attribute?

**Comment by p53** [comment]
@Bogdan00766 did you manage to make it work?
