### ISSUE TITLE
Support for multiple upstreams and clients

### ISSUE THREAD

**Issue by pepellsd** [gogatekeeper/gatekeeper#426]
Hi @p53, I'm search for gateway to shift the responsibility of interaction with kk. 
So in my infrastructure I have some micro-services which I want to protect, I can deal with limitation of single upstream with proxy server, but what about clients? The documentation of kk says "one client represent e.g spa" so I need to create multiple clients for my spa's.
Maybe I don't understand the idea of gogatekeeper and need to implement it for each micro-service in front of, but it seems not right.

**Comment by p53** [comment]
Hi, gatekeeper is small oidc proxy it doesn't have multi stream and multi client configuration, for that it would need major rework, which would need much more time resources and would be not backward compatible, so that would be nice new project ;)

**Comment by p53** [comment]
@pepellsd but you can do setup with one client and multiple upstreams with https://gogatekeeper.github.io/gatekeeper/userguide/#forward-auth
