### ISSUE TITLE
Body is missing from upstreamed request when using OPA

### ISSUE THREAD

**Issue by morelina** [gogatekeeper/gatekeeper#432]
# Title

Body is missing from upstreamed request when using OPA

## Summary

The body of a request (with body) that has been successfully authorized using OPA does not reach the upstream service.

## Environment

- OS: Linux
- Go (e.g. go version) 1.21.6
- Gatekeeper: 2.9.4

## Expected Results

The upstream service receives the request body when the request is successfully authorized.

## Actual Results

The upstream service received no body on a successfully authorized request (that had a body)

## Steps to reproduce

Configure Gogatekeeper to use OPA. 
Configure the corresponding policy that allows a request. 
Send the request with body.

## Additional Information

Javier Moreno Molina <javier.moreno_molina@mercedes-benz.com>, Mercedes-Benz Connectivity Services GmbH

[Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by p53** [comment]
Hi, thanks for issue, will look at it. This is tested in tests ([pkg/testsuite/middleware_test.go](https://github.com/gogatekeeper/gatekeeper/blob/master/pkg/testsuite/middleware_test.go#L2533)), but will test it also manually to check if there is some culprit

**Comment by p53** [comment]
ok found issue, will try to push changes today

**Comment by p53** [comment]
@morelina hi, issue should be fixed, you can try image 2.9.6-rc1
