### ISSUE TITLE
The problem with non Latin (Cyrillic) fonts

### ISSUE THREAD

**Issue by stilet** [gogatekeeper/gatekeeper#446]
# Title 
The problem with non Latin (Cyrillic) fonts

## Summary
The problem with Cyrillic fonts is in the names of groups or roles.
For example, when naming a group (in Keycloak) as a Гарантум, the value in the x-auth-groups header ÐÐ°ÑÐ°Ð½ÑÑÐ¼.
How can I fix it?

**Comment by p53** [comment]
https://stackoverflow.com/a/75998796

**Comment by p53** [comment]
As you can see header values can contain only small subset of characters, only improvement I can make is to reject request if token fields which will be translated to headers will contain other characters than those allowed

**Comment by stilet** [comment]
Thanks! No changes are required. You can close the task.
