### ISSUE TITLE
Question : Can use Gatekeeper with curl ?

### ISSUE THREAD

**Issue by NonneTrapuE** [gogatekeeper/gatekeeper#448]
Hi !

Have a question : Can i log in Gatekeeper with curl or cli commands ?

I test but it don't work, maybe it's because i have wrong config.

Anyone have already test ?

PS : when i test with curl, response is html template of keycloak, not the service in back 

Thanks

**Comment by p53** [comment]
@NonneTrapuE of course you can, how you need to use it depends of what kind of Oauth flow you are using, (code flow=no-redirects=false in gatekeeper, you need to supply cookie jar with proper cookies; password/resource-owner flow=no-redirects=true => send token in Bearer Authentication header)

**Comment by NonneTrapuE** [comment]
Very thanks for your quick answer ! 
I will test quickly :D
