### ISSUE TITLE
Update outdated bootstrap/jquery scripts

### ISSUE THREAD

**Issue by georgeeker** [gogatekeeper/gatekeeper#449]
# Title
Update outdated bootstrap/jquery scripts

## Summary 

Update bootstrap/jquery scripts used within the forbidden template 

## Why?

The scripts are out of date, and have some vulnerabilities 
https://security.snyk.io/package/npm/jquery 
https://security.snyk.io/package/npm/bootstrap 

## How
The forbidden template references these scripts -> https://github.com/gogatekeeper/gatekeeper/blob/master/templates/forbidden.html.tmpl 

## Acceptance criteria

Jquery updated to non vulnerable versions (3.7.1 current latest)
Bootstrap updated to non vulnerable versions (5.3 current latest)

**Comment by p53** [comment]
@georgeeker thanks for creating issue! will update

**Comment by p53** [comment]
@georgeeker updated
