### ISSUE TITLE
Provide helm charts for Kubernetes deployment

### ISSUE THREAD

**Issue by jonkerj** [gogatekeeper/gatekeeper#47]
# Provide helm charts for Kubernetes deployment

## Summary 

Provide a Helm chart to deploy keycloak-gatekeeper on Kubernetes.

## Why?

A lot of people, like me, are/were using keycloak-gatekeeper (or maybe louketo) on Kubernetes and used Helm to simplify deployment. Supplying a Helm chart simplifies this deployment and makes it attractive to migrate from the abandoned incarnations to Gatekeeper.

[Gabibbo97](https://github.com/gabibbo97) has an excellent chart for keycloak-gatekeeper, but K-G has been killed. Also, since the deprecation of `helm/stable`, there is a strong trend towards helm charts being maintained/hosted from the project itself.

## How

I would suggest to copy [Gabibbo97's chart](https://github.com/gabibbo97/charts/tree/master/charts/keycloak-gatekeeper) and use the  [chart-releaser-action](https://github.com/helm/chart-releaser-action) in the workflow to CD the charts. Finally, register the resulting chart museum at [artifacthub.io](https://artifacthub.io/) so everybody can find Gatekeeper.

**Comment by p53** [comment]
this would be nice but there are quite many fixes needed+tests so i think it is low priority for now, but thanks for suggestion :+1:

**Comment by mkilchhofer** [comment]
I have also written a chart and I'd love to contribute it to you :-)

**Comment by p53** [comment]
@mkilchhofer ok, great, just make pull request :)

**Comment by p53** [comment]
@mkilchhofer hmm, thinking, probably it would be better to have separte repo for helm-chart

**Comment by mkilchhofer** [comment]
Yes, both makes sense. I'd use the Github Releases for the helm chart as well, so maybe it makes sense to decouple it and use a separate repo for the .tar.gz files and the software itself.

**Comment by mkilchhofer** [comment]
Here it is: https://artifacthub.io/packages/helm/gogatekeeper/gatekeeper

I think we can close this issue now 😃
