### ISSUE TITLE
Hide sensitive information in logs

### ISSUE THREAD

**Issue by nonvoy** [gogatekeeper/gatekeeper#475]
# Hide sensitive information in GoGatekeeper logs

## Summary 
Hide sensitive information such as email, IP adress, or any PII information in logs.

## Why?
In order to make logs GDPR compliant.

## Acceptance criteria
No PII information should be exposed on logs

**Comment by p53** [comment]
thank you for openin issue! i will look at it what can be done here in some structured way

**Comment by p53** [comment]
hi, i removed emails, client IP from Info/Error messages, replaced with user sub (ID), in verbose mode email and IP are logged (because they are useful for debugging), you can try 2.13.0-rc2 docker image

**Comment by nonvoy** [comment]
Awesome, thanks a lot man!

**Comment by nonvoy** [comment]
We tested it and it is working fine. Thank you very much for quickly implementing this feature!
