### ISSUE TITLE
Error:could not find resource matching path	

### ISSUE THREAD

**Issue by Tistou-ESGI** [gogatekeeper/gatekeeper#476]
# Title

Error:could not find resource matching path	

## Summary

Hi, i'm trying to use Gatekeeper with Keycloak.
I have a keycloak user who is owner of a resource. This resource is member of a client who is configured to work with gatekeeper.
Resource path is "/*" on keycloak AND on Gatekeeper. I enabled UMA in Gatekeeper
But when my user try to click on his resource, it's not working and i sww this error in Gatekeeper logs: 
info	proxy/middleware.go:209	could not find resource matching path..
"path": "/favicon.ico", "method": "GET"}

## Environment

Version of everything that it's running in your environment:
- OS: LXC Debian 11.9
- Kernel (e.g. `uname -a`): 5.15.104-1-pve #1 SMP PVE 5.15.104-1 (2023-03-29T15:51Z) x86_64 GNU/Linux
- Go (e.g. go version)
- Server (e.g. Keycloak or any other IdP): keycloak25.0.1
- Gatekeeper:2.12.1

**Comment by Tistou-ESGI** [comment]
Hi,

when i disable uma mehtod scope, i can access well.
here is my conf:
client-id: SVL1
client-secret: efwefwef
discovery-url: http://keycloak.efwwef.efwwef:8080/realms/master
enable-default-deny: false
encryption-key: fewefwwef
listen: :3000
redirection-url: http://192.168.42.144:3000
upstream-url: http://192.168.42.144:80
resources:
  - uri: /*
    methods:
enable-uma: true
#enable-uma-method-scope: true
#skip-access-token-clientid-check: true
#skip-access-token-issuer-check: true
#verbose: true
#enable-logging: true
enable-refresh-tokens: true
secure-cookie: false


But i need to only added users can access to this resource.
actually anyone can access to it . i want restrict only owner and users added by owner can access to it . 
owner add user throught a scope linked to a permission
thanks

**Comment by p53** [comment]
can you remove resources section and instead have this configuration:

https://gogatekeeper.github.io/gatekeeper/userguide/#example-browser-flow

```
  --enable-default-deny=true
  # we are enabling UMA
  --enable-uma=true
  # we are also enabling using method scope, this is optional,
  # it will check resource in keycloak not just for accessed URL
  # but also for method scope e.g. method:GET, it will return
  # UMA token in cookie only for that URL+method scope,
  # if you don't turn it on it will check just for URL 
  # and will return UMA token in cookie
  # with all scopes
  --enable-uma-method-scope=false
```

Then you must set permissions to allow e.g. group in which your users reside
i can attach screenshots later today how you can configure it, gatekeeper will not check scopes in this configuration
in case you will use `--enable-uma-method-scope=true` it will only try to match scope in form `method:<YOUR_HTTP_METHOD`, it will not match any other scopes, i can attach some screenshots with keycloak authz configuration to show you proper configuration

Anyway i would recommend to use Open Policy Agent for Authorizations, it is much more flexible than UMA/keycloak

**Comment by Tistou-ESGI** [comment]
thanks! it seems to work with your methode.

is it possible to have GUI to make request?

and can we add a timer on a permission ?
for exemple request for 1h only

**Comment by Tistou-ESGI** [comment]
also, is it possible to have multiple owners / aprouver?
thanks

**Comment by p53** [comment]
hmm, not sure i understand what you mean

probably you would like to do this https://www.keycloak.org/docs/latest/authorization_services/index.html#_service_authorization_aat ? For making request for resource i think there is no UI, maybe that would be interesting feature, to make submit request automatically when user would like to access URI, i have to look at that what it would require. I see there is time based policy so you can attach time based policy to your permissions.

**Comment by Tistou-ESGI** [comment]
Hi

Thanks for your reply,

Yes i would like to have a userfriendly interface where users can request access for a webapp.

managers can access to approuve or deny this request.

As a classic bastion, a notification by mail when a request comes and one when your request as been approved.
A duration in the permission request . If approved, the permission would work only for this  duration.

also, i would like several manager (actually only the owner of the resource can approuve) 

Is this things possible?
Thanks

**Comment by p53** [comment]
No as far as i know duration in permission request is not possible, you can configure token expiration time or attach policy to permissions and i don't think approval by several people is possible, as you said it is only possible to approve by resource owner

**Comment by p53** [comment]
hmm from your description i don't understand what are you trying to achieve, can you explain it more precisely, e.g. some diagram maybe would help

**Comment by Tistou-ESGI** [comment]
Its good it works.

i just have a question, how can i forward the client’s ip to the final webserver. Actually my final webserver see the gatekeeper’s ip

thanks

**Comment by p53** [comment]
you should see it in X-Forwarded-For or X-RealIP header

**Comment by Tistou-ESGI** [comment]
Yes my gatekeeper receive the good ip, but when it forwards request, the final webserver see gatekeeper’s ip

**Comment by p53** [comment]
could you provide more details e.g. how many proxies you have before your backend, headers on each of them so that i see what is flow and how headers are rewriten
