### ISSUE TITLE
Gatekeeper ignores X-Forwarded-Uri when Traefik forward-auth is set up

### ISSUE THREAD

**Issue by Lyian** [gogatekeeper/gatekeeper#485]
# Gatekeeper ignores X-Forwarded-Uri when Traefik forward-auth is set up

## Summary

Traefik forward-auth forwards the path header "/", which is expected but also sets the header X-Forwarded-Uri which
seems to be ignored when gatekeeper is configured to protect other paths e.g. "/whoami".

```yaml
resources:
  - uri: /
    roles: 
      - admin
  - uri: /listener
    roles: 
      - admin
  - uri: /whoami
    roles: 
      - testRole
```

Gatekeeper receives the path header "/" which is the only rule evaluated. If I have access to "/" I have access to every 
other resource. 

## Environment
See provided docker-compose example.
[gatekeeper-issue-example.tar.gz](https://github.com/user-attachments/files/16281423/gatekeeper-issue-example.tar.gz)

## Expected Results
I expected that the X-Forwarded-Uri is evaluated when X-Forwarded-Header is set by Traefik when forward-auth is set up.
The configuration for "/whoami" is evaluated, such that only users with the role "testRole" have access.

## Actual Results

Users with permissions to "/" have access to every other resource.

## Steps to reproduce

1. Configure docker-compose file by getting your host.docker.internal ip and set up gatekeeper
2. Start docker-compose file. 
3. Navigate to "http://localhost/"
4. Login with the admin user (username: adminUser, password: adminPassword1)
5. You have access to "/", navigate to "/whoami". You still have access to "/whoami" even though you do not have the role "testRole"
6. Invalidate your session in keycloak
7. Navigate to "localhost/whoami" 
8. Login with test user (username: testUser, password: testPassword1)
9. testUser has role "testRole", but access is not granted, since testUser has no access to "/"

## Additional Information

* You have to add an entry in the compose.yaml file such that gatekeeper has access to keycloak by adding your host.docker.internal ip to the compose.yaml file.

I checked the section in gatekeeper source `pkg/keycloak/proxy/middleware.go` line 106-114

```go 
  authzPath := req.URL.Path
  if noProxy {
      authzPath = req.Header.Get("X-Forwarded-URI")
      if authzPath == "" {
        scope.Logger.Error(apperrors.ErrForwardAuthMissingHeaders.Error())
        accessForbidden(wrt, req)
        return
        }
  }
```

and it seems gatekeeper actually evaluates the X-Forwarded-Uri but I was not able to understand the rest of the go code and why it actually does not work.

It might have something to do with case sensitivity since gatekeeper evaluates `X-Forwarded-URI` instead of `X-Forwarded-Uri` which Traefik sets.

Thank you for your help!
[gatekeeper-issue-example.tar.gz](https://github.com/user-attachments/files/16281423/gatekeeper-issue-example.tar.gz)

**Comment by p53** [comment]
Hi, thanks for opening issue, capitalization of headers should not matter because golang always cannocalize them https://ron-liu.medium.com/what-canonical-http-header-mean-in-golang-2e97f854316d, i will have a look what can be issue.

**Comment by p53** [comment]
Hi, ok checked the code, part of the code which you checked is related to external authorization, e.g. using OPA/UMA. You are using static authorization, problem is this, gogatekeeper attaches static authorization middleware to specific URI, when you have enabled noproxy=true, traeffic sends forward auth to gatekeeper with URI '/' not actual authenticated URI, so above mechanism will be not working, to make it work you can use resource.Headers to match against actual X-Forwarded-URI: '/somepath'

**Comment by p53** [comment]
another possibility would be to configure traeffic to send actual paths to forward-auth target, but as far as i saw this is not possible, but i am not proficient in traeffic so maybe there is some possibility

**Comment by krankkkk** [comment]
> another possibility would be to configure traeffic to send actual paths to forward-auth target, but as far as i saw this is not possible, but i am not expert in traeffic so maybe there is some possibility

Traefik sadly doesn't support sending the actual path in the request beyond the header 

> Hi, ok checked the code, part of the code which you checked is related to external authorization, e.g. using OPA/UMA. You are using static authorization, problem is this, gogatekeeper attaches static authorization middleware to specific URI, when you have enabled noproxy=true, traeffic sends forward auth to gatekeeper with URI '/' not actual authenticated URI, so above mechanism will be not working, to make it work you can use resource.Headers to match against actual X-Forwarded-URI: '/somepath'

We tried the header matching, but we had 2 issues:
 - It doesn't support Regex so we cant have subpaths. i.e. `X-Forwarded-URI: /test*`
 - It will still match the uri with `/`, and you cannot omit the uri
 
 I found a [solution](https://github.com/iits-consulting/gatekeeper/pull/1/commits/0fac0b28b2aa17205ec7b1c31962f44ec9a47130) that works for us in this specific use-case. 
But since I'm not as fluent in golang, it's probably not polished enough to be merged here. 
Still might be a good starting point

**Comment by p53** [comment]
:) thanks for solution, interesting, i need to check why your solution works and if it works in proper way

**Comment by p53** [comment]
@krankkkk hi i checked why it is working this way and it is because child router matching is done after common (parent) middleware, i expected reverse, i created new rc release 2.14.0-rc1, you can test it, there is docker image available

**Comment by krankkkk** [comment]
@p53 That version seems to work as intended 👍🏽

**Comment by Lyian** [comment]
Thank you for
