### ISSUE TITLE
Handling SIGINT properly

### ISSUE THREAD

**Issue by arielmorelli** [gogatekeeper/gatekeeper#499]
# Title

Handling SIGINT properly

## Summary 

When a signal is received, the server is finished without properly closing it.

## Why?

When requests still open, closing the server will break the client.

## How

Close the server after a signal is received.

## Acceptance criteria

[ ] Send a request to a slow endpoint. Send a signal. The server should not die unless a timeout.

**Comment by p53** [comment]
Hi,

yup thanks for issue! i am aware of this.

**Comment by arielmorelli** [comment]
@p53 what is the releasing process for this feature? Do you have a ETA?

**Comment by p53** [comment]
@arielmorelli I can release it today/tomorrow, will add some updates to deps
