### ISSUE TITLE
Gogatekeeper + keycloak+ redis

### ISSUE THREAD

**Issue by YuesIt17** [gogatekeeper/gatekeeper#507]
Hello! 
I have a problem with the gatekeeper in my app. 

We have settings of accsess token in keyclock, where his lifetime is 10 minutes and lifetime of refresh token is 6 hours.

But after 10 minutes, when access token is expired, api requests get 303 status and happend redirect to page authorization
![image](https://github.com/user-attachments/assets/f89fb50d-2fc7-4daa-bf0d-78a23516f13c)
![image](https://github.com/user-attachments/assets/61fe8805-331a-4e08-8b0e-1993486ba4ed)

And then i see logs of gatekeeper 
![image](https://github.com/user-attachments/assets/87302698-9fcc-4ea1-b61f-3cdf075fd2ac)

My setting:
- for keycloak
![image](https://github.com/user-attachments/assets/1b1a5ba5-8274-4f52-836b-789b8352b115)
![image](https://github.com/user-attachments/assets/ee2856df-c596-4d0c-823f-7691f1820e27)

- for gatekeeper
```
 discovery-url: mykeycloack/.well-known/openid-configuration
    redirection-url: https://my-app
    upstream-url: http://my-app
    client-id: ...
    client-secret:...
    enable-metrics: true
    enable-refresh-tokens: true
    encryption-key: ....
    skip-upstream-tls-verify: true
    skip-openid-provider-tls-verify: true
    enable-id-token-cookie: true
    server-read-timeout=600s
    server-write-timeout=600s
    upstream-response-header-timeout=600s
    post-logout-redirect-uri: https://my-app
    cookie-access-name: ...
    cookie-refresh-name: ...
    cookie-oauth-state-name:...
    cookie-request-uri-name: ...
    cors-origins:....
    listen-admin: :4000
    listen: :5555
    store-url: redis://my-redis:6379/1
```
what am i doing wrong?

**Comment by p53** [comment]
Hi, thank you for opening issue! Will look at it, looks like it cannot retrieve access token from redis, what version of redis are you using?

**Comment by p53** [comment]
@YuesIt17 i tested it now with different token/refresh token lifetimes (30s - Access token, 10 min Refresh; 3 min. Access, 10 min Refresh; 30s Access, 6h Refresh) and with these options, trying to make them closest to your and it was working without problems:

```
                "--discovery-url=http://127.0.0.1:8081/realms/xxx/.well-known/openid-configuration",
                "--client-id=xxx",
                "--client-secret=xxx",
                "--upstream-url=http://127.0.0.1:8082",
                "--listen=0.0.0.0:5000",
                "--enable-metrics=true",
                "--enable-refresh-tokens=true",
                "--encryption-key=xxx",
                "--skip-upstream-tls-verify=true",
                "--skip-openid-provider-tls-verify=true",
                "--enable-id-token-cookie=true",
                "--server-read-timeout=600s",
                "--server-write-timeout=600s",
                "--upstream-response-header-timeout=600s",
                "--listen-admin=0.0.0.0:6000",
                "--scopes=openid",
                "--secure-cookie=false",
                "--verbose=true",
                "--store-url=redis://localhost:6379/1",
                "--redirection-url=http://localhost:5000",
```
What version of gatekeeper are you using+what version of redis+can you enable `verbose: true` and post logs, thx

**Comment by p53** [comment]
@YuesIt17 i see you are probably making ajax request, do you have withCredentials set to true?

**Comment by YuesIt17** [comment]
> @YuesIt17 i see you are probably making ajax request, do you have withCredentials set to true?

Yes, i make a request via axios and set withCredentials=true
![image](https://github.com/user-attachments/assets/d30c0e80-78ee-4c88-8e13-14a8790aa2ad)

**Comment by YuesIt17** [comment]
> @YuesIt17 i tested it now with different token/refresh token lifetimes (30s - Access token, 10 min Refresh; 3 min. Access, 10 min Refresh; 30s Access, 6h Refresh) and with these options, trying to make them closest to your and it was working without problems:
> 
> ```
>                 "--discovery-url=http://127.0.0.1:8081/realms/xxx/.well-known/openid-configuration",
>                 "--client-id=xxx",
>                 "--client-secret=xxx",
>                 "--upstream-url=http://127.0.0.1:8082",
>                 "--listen=0.0.0.0:5000",
>                 "--enable-metrics=true",
>                 "--enable-refresh-tokens=true",
>                 "--encryption-key=xxx",
>                 "--skip-upstream-tls-verify=true",
>                 "--skip-openid-provider-tls-verify=true",
>                 "--enable-id-token-cookie=true",
>                 "--server-read-timeout=600s",
>                 "--server-write-timeout=600s",
>                 "--upstream-response-header-timeout=600s",
>                 "--listen-admin=0.0.0.0:6000",
>                 "--scopes=openid",
>                 "--secure-cookie=false",
>                 "--verbose=true",
>                 "--store-url=redis://localhost:6379/1",
>                 "--redirection-url=http://localhost:5000",
> ```
> 
> Which version of gatekeeper are you using+what version of redis+can you enable `verbose: true` and post logs, thx

We use version of apps:
- gogatekeeper: 2.14.3
- redis:7.4.0-debian-12-r4

I have set `verbose: true` and am monitoring logs (I haven't caught it yet)

**Comment by p53** [comment]
@YuesIt17 i see also that in screenshots you have cors errors+i see in your last update logs: "Actual request no headers added: missing origin" - cookies are also in headers so they will be missing. Not sure about your app setup but you can adjust cors settings e.g. https://github.com/gogatekeeper/gatekeeper/issues/384#issuecomment-1824339661

**Comment by YuesIt17** [comment]
> @YuesIt17 i see also that in screenshots you have cors errors+i see in your last update logs: "Actual request no headers added: missing origin" - cookies are also in headers so they will be missing. Not sure about your app setup but you can adjust cors settings e.g. [#384 (comment)](https://github.com/gogatekeeper/gatekeeper/issues/384#issuecomment-1824339661). I was testing without using javascript (not having frontend+backend setup), so this might be difference between our setups causing you trouble

Ok, thanks! I will see cors error.
And i have tried to draw scheme of our app for to understand interaction with gogatekeeper
Maybe i'm wrong
![image](https://github.com/user-attachments/assets/90c9ddba-0d9c-4c63-ba35-89cbebf8e724)

**Comment by p53** [comment]
why you have there CORS errors? are you using different domains for web frontend/backend?

**Comment by p53** [comment]
@YuesIt17  did you add all of those cors options similar to what is in comment https://github.com/gogatekeeper/gatekeeper/issues/384#issuecomment-1824339661 ? :
```
- "--cors-headers=*"
- "--cors-origins=<give here your origins>"
- "--cors-methods=POST,OPTIONS,<your methods>"
- "--cors-max-age=86400s"
- "--cors-credentials=true"
```

**Comment by YuesIt17** [comment]
> @YuesIt17 did you add all of those cors options similar to what is in comment [#384 (comment)](https://github.com/gogatekeeper/gatekeeper/issues/384#issuecomment-1824339661) ? :
> 
> ```
> - "--cors-headers=*"
> - "--cors-origins=<give here your origins>"
> - "--cors-methods=POST,OPTIONS,<your methods>"
> - "--cors-max-age=86400s"
> - "--cors-credentials=true"
> ```
> 
> here you can read about CORS https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Yes, i tried to add those settings to config of gatekeeper
![image](https://github.com/user-attachments/assets/e9212ab5-2d7f-49bc-9aea-0e09c4357f09)

and also i added this cors settings to config of nginx
![image](https://github.com/user-attachments/assets/3fc38a47-f4f5-4703-962d-c65e59c7de42)

and i see those headers in the console
![image](https://github.com/user-attachments/assets/5babb818-4feb-4721-b715-d091f7dc331c)

but those errors of cors are in the logs of gatekeeper for request of api

```
2024-10-09 18:19:15 [cors] 2024/10/09 15:19:15 Handler: Actual request
2024-10-09 18:19:15 [cors] 2024/10/09 15:19:15   Actual request no headers added: missing origin
2024-10-09 18:19:15 2024-10-09T15:19:15.698Z    debug   middleware/oauth.go:60  authentication middleware
2024-10-09 18:19:15 2024-10-09T15:19:15.698Z    debug   session/token.go:168    found the user identity {...}
2024-10-09 18:19:15 2024-10-09T15:19:15.699Z    debug   middleware/security.go:192      access permitted to resource    {"access": "permitted", "email": "...", "expires": 510.300812614, "resource": "/*"}
```

**Comment by p53** [comment]
it is enough to have cors configuration on front proxy, in your case i assume=nginx, if nginx is in front of gatekeeper it is possible that it removes Origin header, message "Actual request no headers added: missing origin" is from cors middleware and it is returned when Origin is empty.  Ff you have this configuration on nginx, nginx should send all headers properly to gatekeeper so it should be working now.

**Comment by YuesIt17** [comment]
> it is enough to have cors configuration on front proxy, in your case i assume=nginx, if nginx is in front of gatekeeper it is possible that it removes Origin header, message "Actual request no headers added: missing origin" is from cors middleware and it is returned when Origin is empty. If you have this configuration on nginx, nginx should send all headers properly to gatekeeper so it should be working now.

Yes, you absolutly rigth. I have added settings of cors to nginx's config
```
server {
	listen 443 ssl;
	server_name somesite.com;
	
	ssl_certificate /etc/ssl/somesite.crt;
	ssl_certificate_key /etc/ssl/somesite.key;
	
	access_log   /var/log/nginx.access_log  main;

	location / {
		proxy_pass         http://gatekeeper-dev:5551/;
		proxy_redirect     off;

		proxy_set_header   Host             $host;
		proxy_set_header   X-Real-IP        $remote_addr;
		add_header         Access-Control-Allow-Origin https://somesite.com;
		add_header         Access-Control-Allow-Credentials true;
               add_header         Access-Control-Allow-Headers *;
               add_header         Access-Control-Allow-Methods *;
		add_header         Access-Control-Max-Age 86400;
		client_max_body_size 			 75M;

		proxy_connect_timeout      70;
		proxy_send_timeout         90;
		proxy_read_timeout         90;

		proxy_busy_buffers_size    512k;
 		proxy_buffers   					 4 512k;
	 	proxy_buffer_size   			 256k;
		charset  koi8-r;
	}

	error_page  404  /404.html;

}
```

**Comment by YuesIt17** [comment]
@p53 how do you think, this architecture is correct?
![image](https://github.com/user-attachments/assets/9631389b-851a-4e15-8adb-ed79d0be30c7)

I.e. i use api of gatekeeper on the frontend (ts+ reactjs):
 - /oauth/expired - for check token
 - /oauth/token - for update token

Maybe i need  to check directly on the keycloak side via 'react-keycloak/web'?

**Comment by YuesIt17** [comment]
> not sure about your picture/architecture: it should be: browser(user) request = frontend.js -> frontend proxy (from your picture your frontend proxy is gogatekeeper??, you said in comments above that it is nginx) -> gatekeeper -> backend (serving your frontend/api?)
> 
> * is your keycloak available to browser(user)=frontend.js? Using /oauth endpoints is enough but you can use also keycloak if you want to expose those endpoints publicly, that's up to you

I changed my scheme. My app is proxied through gogatekeeper, but keycloack has custom authorization page. After login, user is redirected to nginx (which stores the frontend statics) 

![image](https://github.com/user-attachments/assets/7b98f5fd-0207-4f50-9b23-2d2524e11d25)

**Comment by p53** [comment]
simplified picture of arch 
![arch](https://github.com/user-attachments/assets/aba18446-2488-4f24-aaeb-99c7fb567bce)
detailed flow and arch
![arch-complex](https://github.com/user-attachments/assets/d8e557b1-5438-4b71-b41a-b123e996b59e)
it is not nice image, i would need quite more time to make it nice but should be informative pairs of one request/response pairs are in same colour

**Comment by YuesIt17** [comment]
> simplified picture of arch ![arch](https://private-user-images.githubusercontent.com/5985348/377951302-aba18446-2488-4f24-aaeb-99c7fb567bce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MTU4NjQsIm5iZiI6MTcyOTYxNTU2NCwicGF0aCI6Ii81OTg1MzQ4LzM3Nzk1MTMwMi1hYmExODQ0Ni0yNDg4LTRmMjQtYWFlYi05OWM3ZmI1NjdiY2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjJUMTY0NjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzdkNzdjNThiMWY3M2QxODkxNjZkMWE1ODlhODZjNGIwMTZjOTJlYTQ4NWZhZjFlYTE5ZTNjNzY1OTkwMzY0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.qC2XO8o0W7zcpagsMVdSZ7XLHncnbv3xHSALmso8FzY) detailed flow and arch ![arch-complex](https://private-user-images.githubusercontent.com/5985348/377951471-d8e557b1-5438-4b71-b41a-b123e996b59e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MTU4NjQsIm5iZiI6MTcyOTYxNTU2NCwicGF0aCI6Ii81OTg1MzQ4LzM3Nzk1MTQ3MS1kOGU1NTdiMS01NDM4LTRiNzEtYjQxYS1iMTIzZTk5NmI1OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjJUMTY0NjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWViZTVhNjU4OTgxMjc2OWIxM2U1ZjU5M2QzY2I5YWVhMjM1YWJjNzUxZTM4NGYzZjgzMjcyY2NhYjZkNTc4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CQdAw5A93_AzQzGHwC5u1mArREnk-OmDyuAk9wf9buQ) it is not nice image, i would need quite more time to make it nice but should be informative pairs of one request/response pairs are in same colour

Thanks for your help and images, it is very usefull for me👍

My simplified image looks like this
![image](https://github.com/user-attachments/assets/ed3df593-9be1-4dbc-98a4-dbb7fb0ce302)

Will you have a plan to add arch to our gogatekeeper repository page?

**Comment by p53** [comment]
there are different setups which you users might need so architecture is up to the user, there is no single one which fits all user scenarios...so not sure if this should be part of docu, maybe only as example
