### ISSUE TITLE
Setting X-Forwarded-Host header

### ISSUE THREAD

**Issue by gt814** [gogatekeeper/gatekeeper#520]
## Summary
There may be other components in front of the gatekeeper that process the original request.
The step of adding headers on the gatekeeper sets the X-Forwarded-Host header without checking if it is present in the incoming request.
This causes backend services that use the X-Forwarded-Host header to not work.

## Expected Results
The original value of the X-Forwarded-Host header must be preserved if it was passed.

## Actual Results
GoGatekeeper rewrites the value of the X-Forwarded-Host header in an incoming request to the hostname where GoGatekeeper is installed.

## Additional Information

Source code:
```
	// @step: add the proxy forwarding headers
	req.Header.Set("X-Real-IP", utils.RealIP(req))
	if xff := req.Header.Get(constant.HeaderXForwardedFor); xff == "" {
		req.Header.Set("X-Forwarded-For", utils.RealIP(req))
	} else {
		req.Header.Set("X-Forwarded-For", xff)
	}
	req.Header.Set("X-Forwarded-Host", req.Host)
	req.Header.Set("X-Forwarded-Proto", req.Header.Get("X-Forwarded-Proto"))
```

UP:
problem in line
`req.Header.Set("X-Forwarded-Host", req.Host)`

**Comment by p53** [comment]
@gt814 Hi thanks for opening issue! Actually as you can see it checks if header is present and sets it back to current value in else condition (this else branch is redundant in code) so nothing is overwritten

**Comment by gt814** [comment]
@p53 Hi
I totally agree that there is redundancy in handling the X-Forwarded-For header.

The main problem is in the line of code
`req.Header.Set("X-Forwarded-Host", req.Host)`

X-Forwarded-Host is a header to identify the original host requested by the client.
The host of the entry point and the host where the gatekeeper is installed can be different.

**Comment by gt814** [comment]
The problem can be fixed like this
```
if xfh := req.Header.Get("X-Forwarded-Host"); xfh == "" {
    req.Header.Set("X-Forwarded-Host", req.Host)
}
```
so that the X-Forwarded-Host header is only set if it has not been set previously.

**Comment by p53** [comment]
:) ah ok sorry for misunderstanding didn't read your description properly you were refering to X-Forwarded-Host not X-Forwarded-For,

**Comment by p53** [comment]
@gt814 hi created 3.0.1-rc1 release with fix, there is also docker image

**Comment by gt814** [comment]
> @gt814 hi created 3.0.1-rc1 release with fix, there is also docker image

@p53 Thank you very much!

In the test environment, version 3.0.1-rc1 does not start.
An error occurs: exec /opt/gatekeeper/gatekeeper: exec format error.
I am trying to figure out what is causing the error.

I used version 2.9.4 before and it runs successfully.
Since version 2.9.5 an error appears.

I think the current ticket can be closed. 
I can create a separate one for the problem with the application startup.

**Comment by gt814** [comment]
I figured out why it didn't launch.
I downloaded the image under the ARM architecture and pushed it to the local storage, but the test environment works under the AMD architecture.
