### ISSUE TITLE
Adding upstream-url in the resources settings

### ISSUE THREAD

**Issue by gt814** [gogatekeeper/gatekeeper#536]
## Summary 

I'm confused about the architecture.
On the page https://gogatekeeper.github.io/gatekeeper/ the example architecture looks like the gatekeeper works as a gateway.
But in the gatekeeper settings only one host is possible - upstream-url. 
In practice, this is not enough.
How about adding upstream-url in the resources setting?

Thanks in advance!

## Why?

If we have a gateway that is at the entrance to a Kubernetes cluster and the cluster has modules located in different namespaces, we need the gateway to be able to route requests to different namespace domain names.

## How

Solution options:

1) breaking backward compatibility - set FQDN in uri settings 
```
resources:
- uri: ufr-product-catalog-ui.ufr-product-catalog-dev.svc.cluster.local/products*
```

2) preserving backward compatibility - set the relative path as before, but allow to override the upstream URL.
If upstream-url is specified in the resource, then it overrides the root upstream-url.

```
upstream-url: ufr-product-catalog-ui.ufr-product-catalog-dev.svc.cluster.local
resources:
- uri: /products*
   upstream-url: ufr-product-catalog-ui.ufr-product-catalog-dev.svc.cluster.local
```

**Comment by p53** [comment]
@gt814 hi this is not possible this feature would need to be implemented e.g. as new softwate built above gogatekeeper, for sure there would be next requests to implement virtual host routing, sni matching etc...etc..., I don't have time to implement new project and maintain it but if there is somebody I would be happy to see it

**Comment by gt814** [comment]
@p53 Thanks for your answer!
Behind the gatekeeper we can use other components like envoy or nginx,
but I was confused by the number of components in the chain ))
In my case a sidecar was configured and this required a helm chart for deploying the gatekeeper, different from the helm chart for deploying microservices with business logic.

I understand your point of view and will close this issue.
