### ISSUE TITLE
Add External Authorization

### ISSUE THREAD

**Issue by p53** [gogatekeeper/gatekeeper#80]
# Title
Develop Authorization Plugin

## Summary 

Righ now there is one built-in authorization, it would be nice to enable different type of authorizations by using plugins

## Why?

more flexibility

**Comment by SBlechmann** [comment]
Hey there,
first off, thanks for keeping this project up and running!
Second, is there any intention of implementing such a feature? So that the "authorization" part in keycloak's client configuration can be used?
Thanks :)

**Comment by p53** [comment]
@SBlechmann there are several things to consider here:
1. creating such feature brings additional complexity/time to project
2. more code makes binary bigger
3. i would look more at OPA (open policy agent) as authorizer as it is much more universal than authorization by keycloak
So i am not sure i would like to start it

**Comment by SBlechmann** [comment]
@p53 
I did not know such tool. I'll take a look into, thanks for the advice!
I still got some questions, is is possible to have a chat sometimes?

**Comment by p53** [comment]
@SBlechmann you can write me on discord (link in gogatekeeper README), https://discord.com/invite/zRqVXXTMCv

**Comment by p53** [comment]
@SBlechmann please have a look at #161 , implemented UMA authorization workflow, for now only non-interactive, it would be beneficial if you could test it in your environment and provide feedback

**Comment by p53** [comment]
@SBlechmann made 1.5.0-rc1 release if you would like to try

**Comment by SBlechmann** [comment]
@p53 hey there, hope to find some time to test within the next week. Thanks for providing this feature!
