### ISSUE TITLE
Incorrect refresh token lifetime

### ISSUE THREAD

**Issue by escoand** [gogatekeeper/gatekeeper#81]
# Incorrect refresh token lifetime
## Summary
I'm experiencing incorrect refresh token lifetimes. The logging shows too short lifetimes. But there is no way to log the raw OIDC response to verify it.
```
Login:
2021-05-14T05:04:02.451Z	info	gatekeeper/handlers.go:218	issuing access token for user	{"email": "...", "expires": "2021-05-14T05:34:02Z", "duration": "29m59.548584938s"}
2021-05-14T05:04:02.451Z	debug	gatekeeper/misc.go:147	parsed refresh token with new duration	{"new duration": 43135.548101591}

Refresh:
2021-05-14T05:34:09.621Z	info	gatekeeper/middleware.go:251	accces token for user has expired, attemping to refresh the token	{"client_ip": "192.168.206.95:44356", "email": "..."}
2021-05-14T05:34:10.194Z	info	gatekeeper/middleware.go:304	injecting the refreshed access token cookie	{"client_ip": "192.168.206.95:44356", "cookie_name": "kc-access", "email": "...", "refresh_expires_in": 1798.999883207, "expires_in": 1798.805463817}
2021-05-14T05:34:10.194Z	debug	gatekeeper/middleware.go:324	renew refresh cookie with new refresh token	{"refresh_expires_in": 1798.999883207}
```

But when calling the refresh with curl I can't see these short lifetime values:
```json
### login
{
  "access_token": {
    "exp": 1620977883,
    "iat": 1620976083,
    "jti": "00cfb2fd-bad2-4224-9a68-6703477710de",
    "iss": "https://...",
    "aud": "<CLIENT_ID>",
    "sub": "8e5a64d6-efc2-4133-a863-6948fcf94bca",
    "typ": "Bearer",
    "azp": "<CLIENT_ID>",
    "session_state": "412d459f-5a81-4173-a18f-b31a489fda5c",
    "acr": "1",
    "scope": "email profile",
    "clientId": "<CLIENT_ID>",
    "email_verified": false,
    "clientHost": "...",
    "preferred_username": "service-account-<CLIENT_ID>",
    "clientAddress": "..."
  },
  "expires_in": 1800,
  "refresh_expires_in": 43200,
  "refresh_token": {
    "exp": 1621019283,
    "iat": 1620976083,
    "jti": "9522d0ca-60a3-4b58-8ddc-04c92d563962",
    "iss": "https://...",
    "aud": "https://...",
    "sub": "8e5a64d6-efc2-4133-a863-6948fcf94bca",
    "typ": "Refresh",
    "azp": "<CLIENT_ID>",
    "session_state": "412d459f-5a81-4173-a18f-b31a489fda5c",
    "scope": "email profile"
  },
  "token_type": "bearer",
  "not-before-policy": 0,
  "session_state": "412d459f-5a81-4173-a18f-b31a489fda5c",
  "scope": "email profile"
}

### refresh token
{
  "access_token": {
    "exp": 1620980622,
    "iat": 1620978822,
    "jti": "01e6e709-f79f-4818-acef-c5003d777794",
    "iss": "https://...",
    "aud": "<CLIENT_ID>",
    "sub": "8e5a64d6-efc2-4133-a863-6948fcf94bca",
    "typ": "Bearer",
    "azp": "<CLIENT_ID>",
    "session_state": "412d459f-5a81-4173-a18f-b31a489fda5c",
    "acr": "1",
    "scope": "email profile",
    "clientId": "<CLIENT_ID>",
    "email_verified": false,
    "clientHost": "...",
    "preferred_username": "service-account-<CLIENT_ID>",
    "clientAddress": "..."
  },
  "expires_in": 1800,
  "refresh_expires_in": 40461,
  "refresh_token": {
    "exp": 1621019283,
    "iat": 1620978822,
    "jti": "2ab4bbdb-7e41-4c3d-97f4-ebcf03970823",
    "iss": "https://...",
    "aud": "https://...",
    "sub": "8e5a64d6-efc2-4133-a863-6948fcf94bca",
    "typ": "Refresh",
    "azp": "<CLIENT_ID>",
    "session_state": "412d459f-5a81-4173-a18f-b31a489fda5c",
    "scope": "email profile"
  },
  "token_type": "bearer",
  "not-before-policy": 0,
  "session_state": "412d459f-5a81-4173-a18f-b31a489fda5c",
  "scope": "email profile"
}
```

## Environment
Version of everything that it's running in your environment:
- OS: Linux
- Kernel (e.g. `uname -a`): Linux 9915836b-10fa-476b-6352-9b34 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 Linux
- Go (e.g. go version)
- Server (e.g. Keycloak or any other IdP): Keycloak
- Gatekeeper: 1.3.1 (the official from here)

## Expected Results
Fix the wrong lifetime handling and allow to log the raw OIDC request / response.

## Actual Results
Every now an then it's happening the Keycloak server is responding "Token is not active" on the refresh, but this is happening long time before the configured lifetime of 12h on the Keycloak server. The described situation above doesn't make very confident the problem is completely server sited. 

## Steps to reproduce
Don't know.

**Comment by p53** [comment]
@escoand from your description it is not clear what you were doing, can you paste your curl requests.

what do you mean by:  The logging shows too short lifetimes, which values do you mean.
As i checked there is one inconsistency in logging:

this give duration converted to more human readable form 29m59..s

```
2021-05-14T05:04:02.451Z	info	gatekeeper/handlers.go:218	issuing access token for user	{"email": "...", "expires": "2021-05-14T05:34:02Z", "duration": "29m59.548584938s"}
```

This is duration in seconds:
```
2021-05-14T05:04:02.451Z	debug	gatekeeper/misc.go:147	parsed refresh token with new duration	{"new duration": 43135.548101591}
```

**Comment by p53** [comment]
@escoand i tried to simulate your error message
i set SSO session Idle=refresh token expiration to 2 min.
had access token lifetime=60s
When access token lifetime expires but refresh token is still valid it acquires new access token without problem
when access token expires and also refresh token expires i am getting this message:

```
error   failed to refresh the access token      {"error": "oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"Token is not active\"}"}
```

But it is as it should be because therefore is there SSO session idle = refresh token expiration so that after user does not issue requests=is idle, user should be logged out, refresh token should not be updated on each refresh of access_token

SSO max session=time after which user should be logged out and forced to log in, no matter if user was idle or not

i tried it with 1.3.1 and it behaves as it should

**Comment by p53** [comment]
@escoand what are your settings?

**Comment by escoand** [comment]
Thanks for the fast response. For me there are 2 points

1.  Why is the gatekeeper saying `"refresh_expires_in": 1798.999883207, "expires_in": 1798.805463817` when the refresh timeout it's actually 12h?
2. I would like to request an extended logging. Nice would be a session id to follow the whole flow from login, refresh(s) and timeout to check user complaints. Furthermore the Keycloak server team asked for logs of raw OIDC request / response.

**Comment by jangaraj** [comment]
2. Request ID will be better for tracing - (it can be enabled `enable-request-id` or used from existing header `request-id-header` or completely missing).

**Comment by escoand** [comment]
>     1. Request ID will be better for tracing - (it can be enabled `enable-request-id` or used from existing header `request-id-header` or completely missing).

This is not what I had in mind. I would like to follow one specific user session in the logs. These lines for one out of hundreds sessions:
```
# login
debug	incoming authorization request from client address	{"access_type": {}, "auth_url": "...", "client_ip": "192.168.206.119:35990"}
info	issuing access token for user	{"email": "...", "expires": "2021-05-17T08:03:40Z", "duration": "29m59.504325444s"}
debug	parsed refresh token with new duration	{"new duration": 32955.5038984}
# refresh
info	accces token for user has expired, attemping to refresh the token	{"client_ip": "192.168.206.119:35990", "email": "..."}
info	injecting the refreshed access token cookie	{"client_ip": "192.168.206.119:35990", "cookie_name": "kc-access", "email": "...", "refresh_expires_in": 1799.999919545, "expires_in": 1799.453670536}
debug	renew refresh cookie with new refresh token	{"refresh_expires_in": 1799.999919545}
# refresh failed
error	failed to refresh the access token	{"error": "oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"Token is not active\"}"}
# logout
info	successfully logged out of the endpoint	{"email": "..."}
```

**Comment by p53** [comment]
@escoand yup agree, enhanced logging would be beneficial for everyone, i will update it, could be there are also inconsitencies in logging...

regarding this, i am not sure to which logs you are refering but this should be remaining refresh token token lifetime

```
"refresh_expires_in": 1798.999883207, "expires_in": 1798.805463817
```

at login there should be 12h and this ^ should be remaining, altough there is ```renew refresh cookie with new refresh token```, i will check logging if it is correct (log messages correspond to what code is doing) and also add more debug messages

**Comment by escoand** [comment]
@p53 Thanks. As you can see in my last post at login the duration is `32955.5038984` but with every refresh it's `1800`, similar to access token lifetime.

**Comment by p53** [comment]
@escoand would be better if you could post your settings line by line: access token lifetime, refresh token lifetime, max. session lifetime (from keycloak) and also gatekeeper settings (of course without passwords etc...)

**Comment by p53** [comment]
@escoand yup checked now, logging is bad actually i have 2 min refresh token lifetime and it logs this in debug mode:

```
2021-05-17T10:08:04.086Z        debug   src/middleware.go:324   renew refresh cookie with new refresh token     {"refresh_expires_in": 59.999768789}
```

but functionality is good because when i try to refresh access token with refresh in 2 min refresh token lifetime it works

**Comment by escoand** [comment]
I can show you just the gatekeeper config, the server part is not under my control:

```shell
PROXY_CLIENT_ID=$OIDC_CLIENT_ID \
PROXY_CLIENT_SECRET=$OIDC_CLIENT_SECRET \
PROXY_DISCOVERY_URL=$OIDC_DISCOVERY_URL \
PROXY_ENCRYPTION_KEY=$(echo "$OIDC_CLIENT_SECRET" | sha3sum | head -c32) \
PROXY_LISTEN=0.0.0.0:$PORT \
PROXY_UPSTREAM_URL=http://127.0.0.1:81 \
/usr/local/bin/gatekeeper --config /etc/gatekeeper.yaml
```

```yaml
# https://github.com/gogatekeeper/gatekeeper/blob/master/docs/user-guide.md
enable-default-deny:    true
enable-refresh-tokens:  true
preserve-host:          true
sign-in-page:           /www/login.html
forbidden-page:         /www/forbidden.html
resources:
  - uri:                /css/*
    white-listed:       true
  - uri:                /client.log
    white-listed:       true
  - uri:                /favicon.ico
    white-listed:       true
  - uri:                /health
    white-listed:       true
  - uri:                /img/*
    white-listed:       true
  - uri:                /js/*
    white-listed:       true
  - uri:                /locales/*
    white-listed:       true
  # oauth redirect for pr branches
  - uri:                /pr*
    white-listed:       true
  - uri:                /ws
    white-listed:       true
  - uri:                /*
    groups:
      - ...
```

**Comment by p53** [comment]
@escoand i added some additional logging, fixed refresh token expiration, https://github.com/gogatekeeper/gatekeeper/pull/82

**Comment by escoand** [comment]
@p53 I got in contact with @jangaraj to reproduce the problem in our "real life deployment". The user for whom the "Token not active" problem was reported is being used on multiple PCs with multiple sessions at the same time. Could this problem be caused by some kind of race condition?

**Comment by p53** [comment]
@escoand did you check in logs if refresh token for user was not expired?

**Comment by escoand** [comment]
> @escoand did you check in logs if refresh token for user was not expired?

First, with 1.3.1 it's hard to find the right log for one specific user out of hundreds. And second, the tokens are not in the logs, or did I miss something?

**Comment by escoand** [comment]
@p53 I could deploy a verbose binary, but don't have a working go build environment.

**Comment by p53** [comment]
@escoand i will build image

**Comment by escoand** [comment]
@p53 Thanks for the logging, this is already a huge optimization. I can provide logs now, but it contains sensitive and private data and I won't upload it here. How can I contact you?

**Comment by p53** [comment]
@escoand filter from logs one user which has problem, leave there only beggining of access/refresh token, send me message on discord, link is at main readme
