### ISSUE TITLE
Support for custom cookie names

### ISSUE THREAD

**Issue by OskarsPakers** [gogatekeeper/gatekeeper#94]
## Summary 

Currently, it is possible to configure cookie names for kc-state and kc-access cookies using CookieAccessName and CookieRefreshName configuration parameters, but it is not possible to provide custom names for request_uri and OAuth_Token_Request_State cookies.

## Why?

To be able to run multiple gatekeeper instances under the same domain. Also to be able to upgrade seamlessly from the old version of the keycloak gatekeeper version where cookie domains were set with dots at the beginning. The issue described in the comments
https://issues.redhat.com/browse/KEYCLOAK-10668

## How

I`ll just  add to more configuration variables similar as for access and refresh tokens

## Acceptance criteria

All cookies used by gatekeeper can have custom configured names.

**Comment by p53** [comment]
@OskarsPakers thank you for your pull request! will look at it, will need to add some tests

**Comment by OskarsPakers** [comment]
Thank you very much for accepting and assisting on this in such a short time!

**Comment by p53** [comment]
@OskarsPakers you can test 1.3.3-rc1 image if all works as expected

**Comment by OskarsPakers** [comment]
@p53  Cookie names look good, they are all now customized and they don`t clash with old ones.
This is a nightmare of getting rid of old cookies, because browsers just send both cookies and from the request one cannot determine which cookies is set to which domain.

However, the logout is not working, but it is not due to this change, but due to commit https://github.com/gogatekeeper/gatekeeper/commit/4026f5c53899e100794b28b92d97df0aa2e6f34d 
The parameter is changed from refresh_token= to token=. We use Keycloak and it expects refresh_token parameter to revocation url. Now gatekeepers throws error 500 on logout path
```
error	invalid response from revocation endpoint	{"status": 400, "response": "{\"error\":\"invalid_request\",\"error_description\":\"No refresh token\"}"}
```
It looks like a bug to me

**Comment by p53** [comment]
@OskarsPakers which version of keycloak do you have?

**Comment by p53** [comment]
@OskarsPakers here is also 13 keycloak version docu https://www.keycloak.org/docs/latest/server_admin/index.html#_oidc-endpoints, i cannot find it in old version of keycloak

**Comment by OskarsPakers** [comment]
@p53 Oh. We`re running Keycloak 9.0.13 and the change I guess was introduced in Keycloak 10.
Would you accept a PR to configure this parameter field smth like revocation-token-parameter?
I don`t see another way out as the Keycloak upgrade is a few months in the future for us.

**Comment by p53** [comment]
@OskarsPakers ok, i think more users might have this problem

**Comment by OskarsPakers** [comment]
Ok. An alternate approach might as well be to not do server-to-server revocation but send user to keycloak url /auth/realms/iw-simple/protocol/openid-connect/logout. But there is nothing like this currently in gatekeeper.
I will create a new issue and submit a PR for customizing the revocation token parameter.

**Comment by p53** [comment]
@OskarsPakers there is EnableLogoutRedirect parameter
