### ISSUE TITLE
Logout not working for Keycloak <10

### ISSUE THREAD

**Issue by OskarsPakers** [gogatekeeper/gatekeeper#99]
## Summary

In Keycloak versions below 10, there is no /realms/{realm-name}/protocol/openid-connect/revoke endpoint and the server side logout must be done to /protocol/openid-connect/logout endpoint with refresh token in "refresh_token" parameter. However gatekeeper sends this parameter with name "token".

## Environment
- OS: Debian
- Go (e.g. go version)
- Server (e.g. Keycloak or any other IdP): Keycloak 9.0.13
- Gatekeeper: 1.3.3-rc1

## Expected Results
/oauth/logout should invalidate token 

## Actual Results

Keycloak responds with bad request and gatekeeper fails to logout the user with error in the logs
```
error	invalid response from revocation endpoint	{"status": 400, "response": "{\"error\":\"invalid_request\",\"error_description\":\"No refresh token\"}"}
```

## Steps to reproduce

Use Gatekeeper 1.3.3-rc1 with Keycloak version 9. Perform logout via /oauth/logout

**Comment by p53** [comment]
@OskarsPakers there is EnableLogoutRedirect parameter this would not work for you?

**Comment by OskarsPakers** [comment]
@p53 missed that one. In fact, it works for me. I`ll just redirect users to keycloak logout url.
 I think it is not worth implementing a workaround for the revocation endpoint then.
